// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen5.h"
#include "screens/ui_Screen6.h"
#include "screens/ui_Screen4.h"


///////////////////// VARIABLES ////////////////////

// EVENTS
typedef struct {
    char phone[20];
    char password[50];
} User;

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_im6_png);    // assets/im6.png
LV_IMG_DECLARE(ui_img_3_png);      // assets/3.png
LV_IMG_DECLARE(ui_img_im4_png);    // assets/im4.png
LV_IMG_DECLARE(ui_img_im1_png);    // assets/im1.png

// FONTS
LV_FONT_DECLARE(ui_font_myy2);


// ==================== 全局 UI 对象声明 ====================
// 如果这些变量在各自的 .h 文件中已经声明，这里重复声明会导致"变暗"
// 但为了确保链接成功，我们在这里统一声明

// Screen1 对象
extern lv_obj_t * ui_Screen1;

// Screen2 对象
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label15;

// Screen3 对象
extern lv_obj_t * ui_Screen3;

// Screen4 对象
extern lv_obj_t * ui_Screen4;

// Screen5 对象
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Keyboard3;
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_TextArea6;
extern lv_obj_t * ui_TextArea7;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label17;

// Screen6 对象
extern lv_obj_t * ui_Screen6;

//Screen7对象
extern lv_obj_t * ui_Screen7;
void ui_Screen7_screen_init(void);
void ui_Screen7_screen_destroy(void);
void ui_event_whackamole(lv_event_t * e);

// ==================== 屏幕初始化函数声明 ====================
void ui_Screen1_screen_init(void);
void ui_Screen1_screen_destroy(void);

void ui_Screen2_screen_init(void);
void ui_Screen2_screen_destroy(void);

void ui_Screen3_screen_init(void);
void ui_Screen3_screen_destroy(void);

void ui_Screen4_screen_init(void);
void ui_Screen4_screen_destroy(void);

void ui_Screen5_screen_init(void);
void ui_Screen5_screen_destroy(void);

void ui_Screen6_screen_init(void);
void ui_Screen6_screen_destroy(void);


// ==================== 事件函数声明 ====================
// Screen2 事件
void ui_event_Screen2(lv_event_t * e);
void ui_event_TextArea1(lv_event_t * e);
void ui_event_TextArea2(lv_event_t * e);
void ui_event_Button1(lv_event_t * e);
void ui_event_Button5(lv_event_t * e);
void ui_event_Button6(lv_event_t * e);
void ui_event_Button7(lv_event_t * e);
void ui_event_Label14(lv_event_t * e);

// Screen5 事件
void ui_event_Screen5(lv_event_t * e);
void ui_event_TextArea5(lv_event_t * e);
void ui_event_TextArea6(lv_event_t * e);
void ui_event_TextArea7(lv_event_t * e);
void ui_event_Button3(lv_event_t * e);
void ui_event_Button9(lv_event_t * e);


// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif