// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <string.h> 
#include <time.h>

static lv_obj_t * time_label = NULL;
static lv_timer_t * time_timer = NULL;

lv_obj_t * ui_Screen4;

static void update_time_cb(lv_timer_t * t)
{
    if(time_label) {
        time_t now = time(NULL);
        struct tm *tm_info = localtime(&now);
        char time_str[16];
        strftime(time_str, sizeof(time_str), "%H:%M", tm_info);  // 或 "%H:%M:%S"
        lv_label_set_text(time_label, time_str);
    }
}

static lv_obj_t * cells[4][4];
static int board[4][4] = {0};
static lv_obj_t * label_score;
static int score = 0;
static int game_over_flag = 0;

// 自定义弹窗相关
static lv_obj_t * popup_box = NULL;
static lv_obj_t * popup_mask = NULL;

// ========== 函数前置声明 ==========
static void spawn(void);
static void update_ui(void);
static lv_color_t get_color(int v);
static int is_game_over(void);
static void show_game_over(void);
static void reset_game(void);

/* ===== 重置游戏 ===== */
static void reset_game(void)
{
    // 重置游戏状态
    memset(board, 0, sizeof(board));
    score = 0;
    game_over_flag = 0;
    
    // 关闭可能存在的弹窗
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
    
    // 重新生成初始数字
    spawn();
    spawn();
    update_ui();
}

/* ===== 自定义弹窗关闭 ===== */
static void close_popup_handler(lv_event_t * e)
{
    LV_UNUSED(e);
    
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
}

/* ===== 再来一局按钮事件 ===== */
static void restart_game_event(lv_event_t * e)
{
    LV_UNUSED(e);
    
    // 重置游戏
    reset_game();
    
    // 关闭弹窗
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
}

/* ===== 返回按钮事件（弹窗内） ===== */
static void popup_back_event(lv_event_t * e)
{
    LV_UNUSED(e);
    
    // 关闭弹窗
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
    
    // 返回登录界面
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, NULL);
}

/* ===== 刷新UI ===== */
static void update_ui(void)
{
    char buf[32];
    sprintf(buf, "Score: %d", score);
    lv_label_set_text(label_score, buf);

    for(int i = 0; i < 4; i++) {
        for(int j = 0; j < 4; j++) {
            char num[8];
            if(board[i][j] == 0)
                num[0] = '\0';
            else
                sprintf(num, "%d", board[i][j]);

            lv_obj_t * label = lv_obj_get_child(cells[i][j], 0);

            lv_label_set_text(label, num);

            lv_obj_set_style_bg_opa(cells[i][j], LV_OPA_COVER, 0);
            lv_color_t bg = get_color(board[i][j]);
            lv_obj_set_style_bg_color(cells[i][j], bg, 0);

            if(board[i][j] <= 4) {
                lv_obj_set_style_text_color(label, lv_color_hex(0x776E65), 0);
            } else {
                lv_obj_set_style_text_color(label, lv_color_hex(0xFFFFFF), 0);
            }
        }
    }
}

static lv_color_t get_color(int v)
{
    switch(v) {
        case 2: return lv_color_hex(0xEEE4DA);
        case 4: return lv_color_hex(0xEDE0C8);
        case 8: return lv_color_hex(0xF2B179);
        case 16: return lv_color_hex(0xF59563);
        case 32: return lv_color_hex(0xF67C5F);
        case 64: return lv_color_hex(0xF65E3B);
        case 128: return lv_color_hex(0xEDCF72);
        case 256: return lv_color_hex(0xEDCC61);
        case 512: return lv_color_hex(0xEDC850);
        case 1024: return lv_color_hex(0xEDC53F);
        case 2048: return lv_color_hex(0xEDC22E);
        default: return lv_color_hex(0xCDC1B4);
    }
}

/* ===== 随机生成 ===== */
static void spawn(void)
{
    int empty[16][2];
    int cnt = 0;

    for(int i = 0; i < 4; i++)
        for(int j = 0; j < 4; j++)
            if(board[i][j] == 0) {
                empty[cnt][0] = i;
                empty[cnt][1] = j;
                cnt++;
            }

    if(cnt == 0) return;

    int r = rand() % cnt;
    int x = empty[r][0];
    int y = empty[r][1];

    board[x][y] = (rand() % 2) ? 2 : 4;
}

/* ===== 左移 ===== */
static void move_left(void)
{
    for(int i = 0; i < 4; i++) {
        for(int j = 1; j < 4; j++) {
            if(board[i][j] == 0) continue;

            int k = j;
            while(k > 0 && board[i][k - 1] == 0) {
                board[i][k - 1] = board[i][k];
                board[i][k]     = 0;
                k--;
            }

            if(k > 0 && board[i][k - 1] == board[i][k]) {
                board[i][k - 1] *= 2;
                score += board[i][k - 1];
                board[i][k] = 0;
            }
        }
    }
}

/* ===== 右移 ===== */
static void move_right(void)
{
    for(int i = 0; i < 4; i++) {
        for(int j = 2; j >= 0; j--) {
            if(board[i][j] == 0) continue;

            int k = j;
            while(k < 3 && board[i][k + 1] == 0) {
                board[i][k + 1] = board[i][k];
                board[i][k]     = 0;
                k++;
            }

            if(k < 3 && board[i][k + 1] == board[i][k]) {
                board[i][k + 1] *= 2;
                score += board[i][k + 1];
                board[i][k] = 0;
            }
        }
    }
}

/* ===== 上移 ===== */
static void move_up(void)
{
    for(int j = 0; j < 4; j++) {
        for(int i = 1; i < 4; i++) {
            if(board[i][j] == 0) continue;

            int k = i;
            while(k > 0 && board[k - 1][j] == 0) {
                board[k - 1][j] = board[k][j];
                board[k][j]     = 0;
                k--;
            }

            if(k > 0 && board[k - 1][j] == board[k][j]) {
                board[k - 1][j] *= 2;
                score += board[k - 1][j];
                board[k][j] = 0;
            }
        }
    }
}

/* ===== 下移 ===== */
static void move_down(void)
{
    for(int j = 0; j < 4; j++) {
        for(int i = 2; i >= 0; i--) {
            if(board[i][j] == 0) continue;

            int k = i;
            while(k < 3 && board[k + 1][j] == 0) {
                board[k + 1][j] = board[k][j];
                board[k][j]     = 0;
                k++;
            }

            if(k < 3 && board[k + 1][j] == board[k][j]) {
                board[k + 1][j] *= 2;
                score += board[k + 1][j];
                board[k][j] = 0;
            }
        }
    }
}

/* ===== 返回按钮 ===== */
static void back_event(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        // 关闭可能存在的弹窗
        if(popup_mask) {
            lv_obj_del(popup_mask);
            popup_mask = NULL;
        }
        if(popup_box) {
            lv_obj_del(popup_box);
            popup_box = NULL;
        }
        
        // 返回登录界面
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, NULL);
    }
}

/* ===== 创建棋盘 ===== */
static void create_board(void)
{
    int size = 100;

    lv_obj_t * board_obj = lv_obj_create(ui_Screen4);
    lv_obj_set_size(board_obj, 450, 450);
    lv_obj_center(board_obj);
    lv_obj_set_style_pad_all(board_obj, 5, 0);
    lv_obj_set_style_bg_color(board_obj, lv_color_hex(0xBBADA0), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(board_obj, 255, LV_PART_MAIN);
    lv_obj_set_style_border_width(board_obj, 0, LV_PART_MAIN);
    lv_obj_set_style_radius(board_obj, 10, LV_PART_MAIN);

    for(int i = 0; i < 4; i++) {
        for(int j = 0; j < 4; j++) {
            lv_obj_t * cell = lv_button_create(board_obj);
            lv_obj_set_size(cell, size, size);
            lv_obj_set_pos(cell, j * 110 + 5, i * 110 + 5);
            lv_obj_set_style_radius(cell, 8, LV_PART_MAIN);
            lv_obj_set_style_bg_color(cell, lv_color_hex(0xCDC1B4), LV_PART_MAIN);
            lv_obj_set_style_shadow_width(cell, 0, LV_PART_MAIN);
            lv_obj_set_style_border_width(cell, 0, LV_PART_MAIN);

            lv_obj_t * label = lv_label_create(cell);
            lv_label_set_text(label, "");
            lv_obj_center(label);
            lv_obj_set_style_text_font(label, &ui_font_myy2, LV_PART_MAIN);

            cells[i][j] = cell;
        }
    }
}

/* ===== 滑动逻辑 ===== */
static void gesture_event(lv_event_t * e)
{
    // 如果游戏已结束，不响应滑动
    if(game_over_flag) return;
    
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
    int moved = 0;
    int old_board[4][4];
    
    // 保存移动前的棋盘状态
    memcpy(old_board, board, sizeof(board));
    int old_score = score;

    if(dir == LV_DIR_LEFT) move_left();
    else if(dir == LV_DIR_RIGHT) move_right();
    else if(dir == LV_DIR_TOP) move_up();
    else if(dir == LV_DIR_BOTTOM) move_down();
    else return;  // 不是有效的滑动方向
    
    // 检查棋盘是否有变化
    if(memcmp(old_board, board, sizeof(board)) != 0) {
        spawn();
        update_ui();
        
        if(is_game_over()) {
            game_over_flag = 1;
            show_game_over();
        }
    }
}

/* ===== 游戏结束判断 ===== */
static int is_game_over(void)
{
    for(int i = 0; i < 4; i++)
        for(int j = 0; j < 4; j++)
            if(board[i][j] == 0) return 0;

    for(int i = 0; i < 4; i++) {
        for(int j = 0; j < 4; j++) {
            if(i < 3 && board[i][j] == board[i + 1][j]) return 0;
            if(j < 3 && board[i][j] == board[i][j + 1]) return 0;
        }
    }
    return 1;
}

/* ===== 显示游戏结束弹窗 ===== */
static void show_game_over(void)
{
    // 如果已有弹窗，先关闭
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
    
    // 创建背景遮罩
    popup_mask = lv_obj_create(lv_layer_top());
    lv_obj_set_size(popup_mask, LV_PCT(100), LV_PCT(100));
    lv_obj_set_style_bg_color(popup_mask, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(popup_mask, 100, LV_PART_MAIN);
    lv_obj_set_style_border_width(popup_mask, 0, LV_PART_MAIN);
    lv_obj_add_event_cb(popup_mask, close_popup_handler, LV_EVENT_CLICKED, NULL);
    
    // 创建弹窗容器
    popup_box = lv_obj_create(lv_layer_top());
    lv_obj_set_size(popup_box, 350, 220);
    lv_obj_set_style_bg_color(popup_box, lv_color_hex(0xFAF8EF), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(popup_box, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(popup_box, 20, LV_PART_MAIN);
    lv_obj_set_style_border_width(popup_box, 2, LV_PART_MAIN);
    lv_obj_set_style_border_color(popup_box, lv_color_hex(0x8F7A66), LV_PART_MAIN);
    lv_obj_set_style_shadow_width(popup_box, 20, LV_PART_MAIN);
    lv_obj_set_style_shadow_color(popup_box, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_shadow_opa(popup_box, 100, LV_PART_MAIN);
    lv_obj_center(popup_box);
    
    // 创建标题
    lv_obj_t * title = lv_label_create(popup_box);
    lv_label_set_text(title, "游戏结束!");
    lv_obj_set_style_text_color(title, lv_color_hex(0x776E65), LV_PART_MAIN);
    lv_obj_set_style_text_font(title, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_align(title, LV_ALIGN_TOP_MID, 0, 20);
    
    // 创建分数文本
    char score_msg[64];
    sprintf(score_msg, "得分: %d", score);
    lv_obj_t * score_text = lv_label_create(popup_box);
    lv_label_set_text(score_text, score_msg);
    lv_obj_set_style_text_color(score_text, lv_color_hex(0x776E65), LV_PART_MAIN);
    lv_obj_set_style_text_font(score_text, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_align(score_text, LV_ALIGN_CENTER, 0, -10);
    
    // 创建按钮容器
    lv_obj_t * btn_container = lv_obj_create(popup_box);
    lv_obj_set_size(btn_container, 280, 50);
    lv_obj_set_style_bg_opa(btn_container, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(btn_container, 0, LV_PART_MAIN);
    lv_obj_set_style_pad_all(btn_container, 0, LV_PART_MAIN);
    lv_obj_align(btn_container, LV_ALIGN_BOTTOM_MID, 0, -20);
    lv_obj_set_flex_flow(btn_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(btn_container, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    
    // 再来一局按钮
    lv_obj_t * restart_btn = lv_btn_create(btn_container);
    lv_obj_set_size(restart_btn, 110, 40);
    lv_obj_set_style_bg_color(restart_btn, lv_color_hex(0x8F7A66), LV_PART_MAIN);
    lv_obj_set_style_radius(restart_btn, 20, LV_PART_MAIN);
    
    lv_obj_t * restart_label = lv_label_create(restart_btn);
    lv_label_set_text(restart_label, "再来一局");
    lv_obj_set_style_text_color(restart_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(restart_label, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(restart_label);
    lv_obj_add_event_cb(restart_btn, restart_game_event, LV_EVENT_CLICKED, NULL);
    
    // 返回按钮
    lv_obj_t * back_btn = lv_btn_create(btn_container);
    lv_obj_set_size(back_btn, 110, 40);
    lv_obj_set_style_bg_color(back_btn, lv_color_hex(0x9C8AD6), LV_PART_MAIN);
    lv_obj_set_style_radius(back_btn, 20, LV_PART_MAIN);
    
    lv_obj_t * back_label = lv_label_create(back_btn);
    lv_label_set_text(back_label, "返回");
    lv_obj_set_style_text_color(back_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(back_label, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(back_label);
    lv_obj_add_event_cb(back_btn, popup_back_event, LV_EVENT_CLICKED, NULL);
}

/* ===== UI初始化 ===== */
void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui_Screen4, gesture_event, LV_EVENT_GESTURE, NULL);
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0xFAF8EF), LV_PART_MAIN);

    // 初始化随机数种子
    srand(time(NULL));
    
    // 重置游戏状态（确保每次进入都是新游戏）
    score = 0;
    game_over_flag = 0;
    memset(board, 0, sizeof(board));
    
    // 关闭可能残留的弹窗
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }

    /* 分数显示 */
    label_score = lv_label_create(ui_Screen4);
    lv_obj_align(label_score, LV_ALIGN_TOP_MID, 0, 30);
    lv_obj_set_style_text_font(label_score, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_style_text_color(label_score, lv_color_hex(0x776E65), LV_PART_MAIN);
    lv_label_set_text(label_score, "Score: 0");

    /* 返回按钮 */
    lv_obj_t * back = lv_button_create(ui_Screen4);
    lv_obj_set_size(back, 100, 40);
    lv_obj_align(back, LV_ALIGN_TOP_LEFT, 20, 20);
    lv_obj_set_style_bg_color(back, lv_color_hex(0x8F7A66), LV_PART_MAIN);
    lv_obj_set_style_radius(back, 20, LV_PART_MAIN);

    lv_obj_t * lb = lv_label_create(back);
    lv_label_set_text(lb, "返回");
    lv_obj_set_style_text_color(lb, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(lb, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(lb);
    lv_obj_add_event_cb(back, back_event, LV_EVENT_CLICKED, NULL);

    create_board();

    // 生成初始数字
    spawn();
    spawn();
    update_ui();

        // ===== 右上角时间显示 =====
    time_label = lv_label_create(ui_Screen4);  // X 替换为对应的屏幕编号
    lv_obj_set_style_text_color(time_label, lv_color_hex(0x8F7A66), LV_PART_MAIN);
    lv_obj_set_style_text_font(time_label, &lv_font_montserrat_24, LV_PART_MAIN);
    lv_obj_align(time_label, LV_ALIGN_TOP_RIGHT, -20, 20);

    // 初始化时间显示
    update_time_cb(NULL);

    // 每秒更新一次时间
    time_timer = lv_timer_create(update_time_cb, 1000, NULL);
}

/* ===== 屏幕销毁函数 ===== */
void ui_Screen4_screen_destroy(void)
{
    // 关闭弹窗
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
    
    if(ui_Screen4) {
        lv_obj_del(ui_Screen4);
        ui_Screen4 = NULL;
    }
    
    // 清空指针
    for(int i = 0; i < 4; i++) {
        for(int j = 0; j < 4; j++) {
            cells[i][j] = NULL;
        }
    }
    label_score = NULL;

    if(time_timer) {
    lv_timer_del(time_timer);
    time_timer = NULL;
    }
    time_label = NULL;
}