// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Keyboard4;
extern void ui_event_TextArea8(lv_event_t * e);
extern lv_obj_t * ui_TextArea8;
extern void ui_event_TextArea9(lv_event_t * e);
extern lv_obj_t * ui_TextArea9;
extern void ui_event_TextArea10(lv_event_t * e);
extern lv_obj_t * ui_TextArea10;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label10;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label16;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

