// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "../user_auth.h"

// ========== 外部声明 ==========
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Screen7;
extern void ui_Screen3_screen_init(void);
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern void ui_Screen5_screen_init(void);
extern void ui_Screen6_screen_init(void);
extern void ui_Screen7_screen_init(void);
extern void ui_Screen7_screen_destroy(void);

// ========== UI对象声明 ==========
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label15 = NULL;

// 验证码相关
static lv_obj_t * ui_TextArea_code = NULL;
static lv_obj_t * ui_Label_code = NULL;
static char current_code[5];

// 密码可见性切换按钮
static lv_obj_t * pwd_visibility_btn = NULL;
//static lv_obj_t * pwd_visibility_label = NULL;
static int password_visible = 0;  // 0: 隐藏, 1: 可见

// 时间显示相关
static lv_obj_t * time_label = NULL;
static lv_timer_t * time_timer = NULL;

// 自定义弹窗相关
static lv_obj_t * popup_box = NULL;
static lv_obj_t * popup_mask = NULL;
static lv_timer_t * popup_timer = NULL;

// 屏幕切换参数
typedef struct {
    lv_obj_t **screen;
    lv_scr_load_anim_t anim;
    uint32_t time;
    uint32_t delay;
} ScreenChangeParams;

// 键盘状态
static int keyboard_visible = 0;

// ========== 辅助函数声明 ==========
static void generate_code(void);
static void show_success_message(const char *message, uint32_t auto_close_ms);
static void show_error_message(const char *message, uint32_t auto_close_ms);
static void show_warning_message(const char *message, uint32_t auto_close_ms);

// ========== 密码可见性切换 ==========
// ========== 密码可见性切换 ==========
static void toggle_password_visibility(lv_event_t * e)
{
    LV_UNUSED(e);
    
    password_visible = !password_visible;
    
    if(password_visible) {
        // 显示密码
        lv_textarea_set_password_mode(ui_TextArea2, false);
        lv_obj_set_style_bg_color(pwd_visibility_btn, lv_color_hex(0xB19AB3), LV_PART_MAIN);  // 可见时颜色加深
    } else {
        // 隐藏密码
        lv_textarea_set_password_mode(ui_TextArea2, true);
        lv_obj_set_style_bg_color(pwd_visibility_btn, lv_color_hex(0xD9D1E8), LV_PART_MAIN);  // 隐藏时恢复原色
    }
}
// ========== 时间更新回调 ==========
static void update_time_cb(lv_timer_t * t)
{
    LV_UNUSED(t);
    if(time_label) {
        time_t now = time(NULL);
        struct tm *tm_info = localtime(&now);
        char time_str[16];
        strftime(time_str, sizeof(time_str), "%H:%M", tm_info);
        lv_label_set_text(time_label, time_str);
    }
}

// ========== 生成验证码 ==========
static void generate_code(void)
{
    const char charset[] = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz23456789";
    for(int i = 0; i < 4; i++) {
        current_code[i] = charset[rand() % (sizeof(charset) - 1)];
    }
    current_code[4] = '\0';
    if(ui_Label_code) {
        lv_label_set_text_fmt(ui_Label_code, "%s", current_code);
    }
}

// ========== 验证验证码 ==========
static int verify_code(const char *input)
{
    if(!input || strlen(input) == 0) return 0;
    return (strcmp(input, current_code) == 0);
}

// ========== 自定义弹窗函数 ==========
static void close_popup_handler(lv_event_t * e)
{
    LV_UNUSED(e);
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
}

static void popup_timer_cb(lv_timer_t * timer)
{
    LV_UNUSED(timer);
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
}

static void show_custom_popup(const char *title, const char *message,
                               lv_color_t title_color, lv_color_t bg_color,
                               lv_color_t border_color, lv_color_t btn_color,
                               uint32_t auto_close_ms)
{
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
    
    // 背景遮罩
    popup_mask = lv_obj_create(lv_layer_top());
    lv_obj_set_size(popup_mask, LV_PCT(100), LV_PCT(100));
    lv_obj_set_style_bg_color(popup_mask, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(popup_mask, 100, LV_PART_MAIN);
    lv_obj_set_style_border_width(popup_mask, 0, LV_PART_MAIN);
    lv_obj_add_event_cb(popup_mask, close_popup_handler, LV_EVENT_CLICKED, NULL);
    
    // 弹窗容器
    popup_box = lv_obj_create(lv_layer_top());
    lv_obj_set_size(popup_box, 400, 200);
    lv_obj_set_style_bg_color(popup_box, bg_color, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(popup_box, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(popup_box, 20, LV_PART_MAIN);
    lv_obj_set_style_border_width(popup_box, 2, LV_PART_MAIN);
    lv_obj_set_style_border_color(popup_box, border_color, LV_PART_MAIN);
    lv_obj_set_style_shadow_width(popup_box, 20, LV_PART_MAIN);
    lv_obj_set_style_shadow_color(popup_box, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_shadow_opa(popup_box, 100, LV_PART_MAIN);
    lv_obj_center(popup_box);
    
    // 标题
    lv_obj_t * popup_title = lv_label_create(popup_box);
    lv_label_set_text(popup_title, title);
    lv_obj_set_style_text_color(popup_title, title_color, LV_PART_MAIN);
    lv_obj_set_style_text_font(popup_title, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_align(popup_title, LV_ALIGN_TOP_MID, 0, 15);
    
    // 消息
    lv_obj_t * popup_text = lv_label_create(popup_box);
    lv_label_set_text(popup_text, message);
    lv_obj_set_style_text_color(popup_text, lv_color_hex(0x333333), LV_PART_MAIN);
    lv_obj_set_style_text_font(popup_text, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_width(popup_text, 350);
    lv_label_set_long_mode(popup_text, LV_LABEL_LONG_WRAP);
    lv_obj_align(popup_text, LV_ALIGN_CENTER, 0, 0);
    
    // 关闭按钮
    lv_obj_t * popup_btn = lv_btn_create(popup_box);
    lv_obj_set_size(popup_btn, 80, 35);
    lv_obj_set_style_bg_color(popup_btn, btn_color, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(popup_btn, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(popup_btn, 10, LV_PART_MAIN);
    lv_obj_align(popup_btn, LV_ALIGN_BOTTOM_MID, 0, -15);
    
    lv_obj_t * btn_label = lv_label_create(popup_btn);
    lv_label_set_text(btn_label, "确定");
    lv_obj_set_style_text_color(btn_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(btn_label, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(btn_label);
    
    lv_obj_add_event_cb(popup_btn, close_popup_handler, LV_EVENT_CLICKED, NULL);
    
    if(auto_close_ms > 0) {
        popup_timer = lv_timer_create(popup_timer_cb, auto_close_ms, NULL);
        lv_timer_set_repeat_count(popup_timer, 1);
    }
}

static void show_success_message(const char *message, uint32_t auto_close_ms)
{
    show_custom_popup("成功", message,
                      lv_color_hex(0x2E7D32),
                      lv_color_hex(0xE8F5E9),
                      lv_color_hex(0x4CAF50),
                      lv_color_hex(0x4CAF50),
                      auto_close_ms);
}

static void show_error_message(const char *message, uint32_t auto_close_ms)
{
    show_custom_popup("错误", message,
                      lv_color_hex(0xC62828),
                      lv_color_hex(0xFFEBEE),
                      lv_color_hex(0xF44336),
                      lv_color_hex(0xF44336),
                      auto_close_ms);
}

static void show_warning_message(const char *message, uint32_t auto_close_ms)
{
    show_custom_popup("提示", message,
                      lv_color_hex(0xF57C00),
                      lv_color_hex(0xFFF3E0),
                      lv_color_hex(0xFF9800),
                      lv_color_hex(0xFF9800),
                      auto_close_ms);
}

// ========== 登录验证 ==========
static int validate_login_inputs(const char *phone, const char *password, const char *code, char *err_msg, int err_size)
{
    // 1. 验证账号（电话号码）
    if(!phone || strlen(phone) == 0) {
        snprintf(err_msg, err_size, "请输入电话号码");
        return -1;
    }
    if(!is_valid_phone(phone)) {
        snprintf(err_msg, err_size, "电话号码必须为11位数字");
        return -2;
    }
    
    // 2. 验证密码
    if(!password || strlen(password) == 0) {
        snprintf(err_msg, err_size, "请输入密码");
        return -3;
    }
    
    // 3. 验证验证码
    if(!code || strlen(code) == 0) {
        snprintf(err_msg, err_size, "请输入验证码");
        return -4;
    }
    if(!verify_code(code)) {
        snprintf(err_msg, err_size, "验证码错误");
        return -5;
    }
    
    // 4. 检查账号是否存在
    int idx = find_user_by_phone(phone);
    if(idx < 0) {
        snprintf(err_msg, err_size, "账号不存在，请先注册");
        return -6;
    }
    
    // 5. 验证密码
    const AuthUser *user = get_user_by_index(idx);
    if(!user) {
        snprintf(err_msg, err_size, "系统错误");
        return -7;
    }
    if(strcmp(user->password, password) != 0) {
        snprintf(err_msg, err_size, "密码错误");
        return -8;
    }
    
    return 0;  // 验证通过
}

// ========== 延迟屏幕切换 ==========
static void delayed_screen_change(lv_timer_t * timer)
{
    ScreenChangeParams *params = lv_timer_get_user_data(timer);
    _ui_screen_change(params->screen, params->anim, params->time, params->delay, NULL);
}

// ========== 隐藏键盘 ==========
static void hide_keyboard(void)
{
    if(ui_Keyboard1) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        keyboard_visible = 0;
    }
}

// ========== 显示键盘并绑定目标 ==========
static void show_keyboard_for_textarea(lv_obj_t * ta)
{
    if(!ui_Keyboard1 || !ta) return;
    _ui_keyboard_set_target(ui_Keyboard1, ta);
    _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    keyboard_visible = 1;
}

// ========== 事件函数 ==========
void ui_event_Screen2(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        lv_obj_t * target = lv_event_get_target(e);
        if(target == ui_Screen2) {
            hide_keyboard();
        }
    }
}

void ui_event_TextArea1(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        show_keyboard_for_textarea(ui_TextArea1);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        show_keyboard_for_textarea(ui_TextArea2);
    }
}

static void ui_event_TextArea_code(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        show_keyboard_for_textarea(ui_TextArea_code);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        if(keyboard_visible) {
            show_warning_message("请先关闭键盘", 1500);
            return;
        }
        
        const char *phone = lv_textarea_get_text(ui_TextArea1);
        const char *password = lv_textarea_get_text(ui_TextArea2);
        const char *code = lv_textarea_get_text(ui_TextArea_code);
        
        char err_msg[128];
        int result = validate_login_inputs(phone, password, code, err_msg, sizeof(err_msg));
        
        if(result == 0) {
            show_success_message("登录成功！", 1500);
            
            static ScreenChangeParams params;
            params.screen = &ui_Screen3;
            params.anim = LV_SCR_LOAD_ANIM_MOVE_LEFT;
            params.time = 500;
            params.delay = 0;
            
            lv_timer_t * timer = lv_timer_create(delayed_screen_change, 1500, &params);
            lv_timer_set_repeat_count(timer, 1);
        } else {
            show_error_message(err_msg, 2000);
        }
        
        // 无论登录成功还是失败，都刷新验证码
        generate_code();
    }
}

static void code_click_event(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        generate_code();
    }
}

void ui_event_Button5(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        if(keyboard_visible) {
            show_warning_message("请先关闭键盘", 1500);
            return;
        }
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        if(keyboard_visible) {
            show_warning_message("请先关闭键盘", 1500);
            return;
        }
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        if(keyboard_visible) {
            show_warning_message("请先关闭键盘", 1500);
            return;
        }
        if(ui_Screen4 != NULL) {
            ui_Screen4_screen_destroy();
        }
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_Label14(lv_event_t * e)
{
    LV_UNUSED(e);
}

// ========== 屏幕初始化 ==========
void ui_Screen2_screen_init(void)
{
    srand(time(NULL));
    
    // 加载用户数据
    load_users_from_file();
    
    // 如果没有用户，创建一个测试用户
    if(get_user_count() == 0) {
        add_user("13800138000", "123456");
        printf("[DEBUG] Created test user: 13800138000 / 123456\n");
    }
    
    keyboard_visible = 0;
    password_visible = 0;
    
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_image_src(ui_Screen2, &ui_img_im6_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ===== 键盘 =====
    ui_Keyboard1 = lv_keyboard_create(lv_layer_top());
    lv_obj_set_size(ui_Keyboard1, 1024, 220);
    lv_obj_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0xD1B0D6), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0xB79EBB), LV_PART_ITEMS);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_ITEMS);

    // ===== 账号输入框 =====
    ui_TextArea1 = lv_textarea_create(ui_Screen2);
    lv_obj_set_size(ui_TextArea1, 500, 55);
    lv_obj_align(ui_TextArea1, LV_ALIGN_CENTER, 80, -140);
    lv_textarea_set_placeholder_text(ui_TextArea1, "请输入11位电话号码");
    lv_textarea_set_one_line(ui_TextArea1, true);
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea1, 30, LV_PART_MAIN);

    ui_Label11 = lv_label_create(ui_Screen2);
    lv_obj_align_to(ui_Label11, ui_TextArea1, LV_ALIGN_OUT_LEFT_MID, -20, 0);
    lv_label_set_text(ui_Label11, "账号");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_myy2, LV_PART_MAIN);

    // ===== 密码输入框 =====
    ui_TextArea2 = lv_textarea_create(ui_Screen2);
    lv_obj_set_size(ui_TextArea2, 500, 55);
    lv_obj_align(ui_TextArea2, LV_ALIGN_CENTER, 80, -60);
    lv_textarea_set_placeholder_text(ui_TextArea2, "请输入密码");
    lv_textarea_set_password_mode(ui_TextArea2, true);
    lv_textarea_set_one_line(ui_TextArea2, true);
    lv_obj_set_style_text_font(ui_TextArea2, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea2, 30, LV_PART_MAIN);

    ui_Label12 = lv_label_create(ui_Screen2);
    lv_obj_align_to(ui_Label12, ui_TextArea2, LV_ALIGN_OUT_LEFT_MID, -20, 0);
    lv_label_set_text(ui_Label12, "密码");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_myy2, LV_PART_MAIN);

  // ===== 密码可见性切换按钮（放在密码输入框右侧内部）=====
    pwd_visibility_btn = lv_btn_create(ui_TextArea2);
    lv_obj_set_size(pwd_visibility_btn, 30, 30);
    lv_obj_align(pwd_visibility_btn, LV_ALIGN_RIGHT_MID, -10, 0);
    lv_obj_set_style_bg_color(pwd_visibility_btn, lv_color_hex(0xD9D1E8), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(pwd_visibility_btn, 200, LV_PART_MAIN);
    lv_obj_set_style_radius(pwd_visibility_btn, 15, LV_PART_MAIN);
    lv_obj_set_style_shadow_width(pwd_visibility_btn, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(pwd_visibility_btn, 0, LV_PART_MAIN);
    lv_obj_add_event_cb(pwd_visibility_btn, toggle_password_visibility, LV_EVENT_CLICKED, NULL);

    // ===== 验证码输入框 =====
    ui_TextArea_code = lv_textarea_create(ui_Screen2);
    lv_obj_set_size(ui_TextArea_code, 260, 55);
    lv_obj_align(ui_TextArea_code, LV_ALIGN_CENTER, -20, 20);
    lv_textarea_set_placeholder_text(ui_TextArea_code, "验证码");
    lv_textarea_set_one_line(ui_TextArea_code, true);
    lv_obj_set_style_text_font(ui_TextArea_code, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea_code, 30, LV_PART_MAIN);

    lv_obj_t * label_code_text = lv_label_create(ui_Screen2);
    lv_obj_align_to(label_code_text, ui_TextArea_code, LV_ALIGN_OUT_LEFT_MID, -40, 0);
    lv_label_set_text(label_code_text, "验证码");
    lv_obj_set_style_text_font(label_code_text, &ui_font_myy2, LV_PART_MAIN);

    // ===== 验证码显示按钮 =====
    lv_obj_t * btn_code = lv_button_create(ui_Screen2);
    lv_obj_set_size(btn_code, 120, 55);
    lv_obj_align_to(btn_code, ui_TextArea_code, LV_ALIGN_OUT_RIGHT_MID, 15, 0);
    lv_obj_set_style_bg_color(btn_code, lv_color_hex(0xD1B0D6), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(btn_code, 255, LV_PART_MAIN);
    lv_obj_set_style_border_width(btn_code, 0, LV_PART_MAIN);
    lv_obj_set_style_radius(btn_code, 15, LV_PART_MAIN);

    ui_Label_code = lv_label_create(btn_code);
    lv_label_set_text(ui_Label_code, "----");
    lv_obj_center(ui_Label_code);
    lv_obj_set_style_text_font(ui_Label_code, &lv_font_montserrat_24, LV_PART_MAIN);
    lv_obj_set_style_text_color(ui_Label_code, lv_color_hex(0x333333), LV_PART_MAIN);

    // ===== 按钮区域 =====
    int btn_y = 110;

    // 登录按钮
    ui_Button1 = lv_button_create(ui_Screen2);
    lv_obj_set_size(ui_Button1, 120, 50);
    lv_obj_align(ui_Button1, LV_ALIGN_CENTER, 0, btn_y);
    lv_obj_set_style_radius(ui_Button1, 25, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xB19AB3), LV_PART_MAIN);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_label_set_text(ui_Label1, "登录");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x564A58), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(ui_Label1);

    // 注册按钮
    ui_Button5 = lv_button_create(ui_Screen2);
    lv_obj_set_size(ui_Button5, 100, 50);
    lv_obj_align(ui_Button5, LV_ALIGN_CENTER, -180, btn_y);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_Button5, 1, LV_PART_MAIN);
    lv_obj_set_style_border_color(ui_Button5, lv_color_hex(0xB19AB3), LV_PART_MAIN);
    lv_obj_set_style_radius(ui_Button5, 25, LV_PART_MAIN);

    ui_Label13 = lv_label_create(ui_Button5);
    lv_label_set_text(ui_Label13, "注册");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(ui_Label13);

    // 忘记密码按钮
    ui_Button6 = lv_button_create(ui_Screen2);
    lv_obj_set_size(ui_Button6, 120, 50);
    lv_obj_align(ui_Button6, LV_ALIGN_CENTER, 180, btn_y);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_Button6, 1, LV_PART_MAIN);
    lv_obj_set_style_border_color(ui_Button6, lv_color_hex(0xB19AB3), LV_PART_MAIN);
    lv_obj_set_style_radius(ui_Button6, 25, LV_PART_MAIN);

    ui_Label14 = lv_label_create(ui_Button6);
    lv_label_set_text(ui_Label14, "忘记密码");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(ui_Label14);

    // 2048 按钮
    ui_Button7 = lv_button_create(ui_Screen2);
    lv_obj_set_size(ui_Button7, 100, 50);
    lv_obj_align(ui_Button7, LV_ALIGN_TOP_LEFT, 20, 20);
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xB19AB3), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_Button7, 25, LV_PART_MAIN);

    ui_Label15 = lv_label_create(ui_Button7);
    lv_label_set_text(ui_Label15, "2048");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(ui_Label15);

    // ===== 时间显示 =====
    time_label = lv_label_create(ui_Screen2);
    lv_obj_set_style_text_color(time_label, lv_color_hex(0xB19AB3), LV_PART_MAIN);
    lv_obj_set_style_text_font(time_label, &lv_font_montserrat_24, LV_PART_MAIN);
    lv_obj_align(time_label, LV_ALIGN_TOP_RIGHT, -90, 100);
    update_time_cb(NULL);
    time_timer = lv_timer_create(update_time_cb, 1000, NULL);

    // ===== 事件绑定 =====
    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_TextArea_code, ui_event_TextArea_code, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(btn_code, code_click_event, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_CLICKED, NULL);


    // 在 ui_Screen2_screen_init 函数中，在返回按钮之后添加：

    // ========== 打地鼠按钮（右下角）==========
    lv_obj_t * btn_whackamole = lv_btn_create(ui_Screen2);
    lv_obj_set_width(btn_whackamole, 100);
    lv_obj_set_height(btn_whackamole, 50);
    lv_obj_align(btn_whackamole, LV_ALIGN_BOTTOM_RIGHT, -20, -20);
    lv_obj_add_flag(btn_whackamole, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_remove_flag(btn_whackamole, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(btn_whackamole, 20, LV_PART_MAIN);
    lv_obj_set_style_bg_color(btn_whackamole, lv_color_hex(0xB19AB3), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(btn_whackamole, 255, LV_PART_MAIN);

    lv_obj_t * label_mole = lv_label_create(btn_whackamole);
    lv_label_set_text(label_mole, "打地鼠");
    lv_obj_set_style_text_color(label_mole, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(label_mole, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(label_mole);

    // 添加点击事件跳转到 Screen7
    lv_obj_add_event_cb(btn_whackamole, ui_event_whackamole, LV_EVENT_CLICKED, NULL);

    // 生成初始验证码
    generate_code();
    
    printf("[DEBUG] Screen2 initialized\n");
}

// 打地鼠按钮事件
// 打地鼠按钮事件
void ui_event_whackamole(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        if(keyboard_visible) {
            show_warning_message("请先关闭键盘", 1500);
            return;
        }
        // 先销毁可能存在的旧 Screen7，确保每次都是全新游戏（与 Screen4 一致）
        if(ui_Screen7 != NULL) {
            ui_Screen7_screen_destroy();
        }
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen7_screen_init);
    }
}

// ========== 屏幕销毁 ==========
void ui_Screen2_screen_destroy(void)
{
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
    
    if(time_timer) {
        lv_timer_del(time_timer);
        time_timer = NULL;
    }
    time_label = NULL;
    
    if(ui_Screen2) lv_obj_del(ui_Screen2);
    ui_Screen2 = NULL;
    ui_Keyboard1 = NULL;
    ui_TextArea1 = NULL;
    ui_TextArea2 = NULL;
    ui_TextArea_code = NULL;
    ui_Label_code = NULL;
    ui_Button1 = NULL;
    ui_Label1 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Button5 = NULL;
    ui_Button6 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Button7 = NULL;
    ui_Label15 = NULL;
    pwd_visibility_btn = NULL;
    //pwd_visibility_label = NULL;
    
    keyboard_visible = 0;
    password_visible = 0;
    
    printf("[DEBUG] Screen2 destroyed\n");
}