// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

static lv_obj_t * time_label = NULL;
static lv_timer_t * time_timer = NULL;

// ========== 外部函数声明（使用 Screen2 中的函数）==========
extern void load_users_from_file(void);
extern void save_users_to_file(void);
extern int is_valid_phone(const char *phone);
extern int find_user_by_phone(const char *phone);
extern int add_user(const char *phone, const char *password);

// ========== UI对象声明 ==========
lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_Keyboard3 = NULL;
lv_obj_t * ui_TextArea5 = NULL;
lv_obj_t * ui_TextArea6 = NULL;
lv_obj_t * ui_TextArea7 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Label17 = NULL;

// 密码可见性切换按钮（密码）
static lv_obj_t * pwd_visibility_btn1 = NULL;
static int password_visible1 = 0;

// 密码可见性切换按钮（确认密码）
static lv_obj_t * pwd_visibility_btn2 = NULL;
static int password_visible2 = 0;

// 键盘状态
static int keyboard_visible = 0;

// 自定义弹窗相关
static lv_obj_t * popup_box = NULL;
static lv_obj_t * popup_mask = NULL;
static lv_timer_t * popup_timer = NULL;

static void update_time_cb(lv_timer_t * t)
{
    if(time_label) {
        time_t now = time(NULL);
        struct tm *tm_info = localtime(&now);
        char time_str[16];
        strftime(time_str, sizeof(time_str), "%H:%M", tm_info);
        lv_label_set_text(time_label, time_str);
    }
}

// ========== 密码可见性切换（密码）==========
static void toggle_password_visibility1(lv_event_t * e)
{
    LV_UNUSED(e);
    password_visible1 = !password_visible1;
    if(password_visible1) {
        lv_textarea_set_password_mode(ui_TextArea6, false);
        lv_obj_set_style_bg_color(pwd_visibility_btn1, lv_color_hex(0xB19AB3), LV_PART_MAIN);
    } else {
        lv_textarea_set_password_mode(ui_TextArea6, true);
        lv_obj_set_style_bg_color(pwd_visibility_btn1, lv_color_hex(0xD9C9EF), LV_PART_MAIN);
    }
}

// ========== 密码可见性切换（确认密码）==========
static void toggle_password_visibility2(lv_event_t * e)
{
    LV_UNUSED(e);
    password_visible2 = !password_visible2;
    if(password_visible2) {
        lv_textarea_set_password_mode(ui_TextArea7, false);
        lv_obj_set_style_bg_color(pwd_visibility_btn2, lv_color_hex(0xB19AB3), LV_PART_MAIN);
    } else {
        lv_textarea_set_password_mode(ui_TextArea7, true);
        lv_obj_set_style_bg_color(pwd_visibility_btn2, lv_color_hex(0xD9C9EF), LV_PART_MAIN);
    }
}

// ========== 自定义弹窗函数 ==========
static void close_popup_handler(lv_event_t * e)
{
    LV_UNUSED(e);
    
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
}

static void popup_timer_cb(lv_timer_t * timer)
{
    LV_UNUSED(timer);
    
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
}

static void show_custom_popup(const char *title, const char *message,
                               lv_color_t title_color, lv_color_t bg_color,
                               lv_color_t border_color, lv_color_t btn_color,
                               uint32_t auto_close_ms)
{
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
    
    // 背景遮罩
    popup_mask = lv_obj_create(lv_layer_top());
    lv_obj_set_size(popup_mask, LV_PCT(100), LV_PCT(100));
    lv_obj_set_style_bg_color(popup_mask, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(popup_mask, 100, LV_PART_MAIN);
    lv_obj_set_style_border_width(popup_mask, 0, LV_PART_MAIN);
    lv_obj_add_event_cb(popup_mask, close_popup_handler, LV_EVENT_CLICKED, NULL);
    
    // 弹窗容器
    popup_box = lv_obj_create(lv_layer_top());
    lv_obj_set_size(popup_box, 400, 200);
    lv_obj_set_style_bg_color(popup_box, bg_color, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(popup_box, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(popup_box, 20, LV_PART_MAIN);
    lv_obj_set_style_border_width(popup_box, 2, LV_PART_MAIN);
    lv_obj_set_style_border_color(popup_box, border_color, LV_PART_MAIN);
    lv_obj_set_style_shadow_width(popup_box, 20, LV_PART_MAIN);
    lv_obj_set_style_shadow_color(popup_box, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_shadow_opa(popup_box, 100, LV_PART_MAIN);
    lv_obj_center(popup_box);
    
    // 标题
    lv_obj_t * popup_title = lv_label_create(popup_box);
    lv_label_set_text(popup_title, title);
    lv_obj_set_style_text_color(popup_title, title_color, LV_PART_MAIN);
    lv_obj_set_style_text_font(popup_title, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_align(popup_title, LV_ALIGN_TOP_MID, 0, 15);
    
    // 消息
    lv_obj_t * popup_text = lv_label_create(popup_box);
    lv_label_set_text(popup_text, message);
    lv_obj_set_style_text_color(popup_text, lv_color_hex(0x333333), LV_PART_MAIN);
    lv_obj_set_style_text_font(popup_text, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_width(popup_text, 350);
    lv_label_set_long_mode(popup_text, LV_LABEL_LONG_WRAP);
    lv_obj_align(popup_text, LV_ALIGN_CENTER, 0, 0);
    
    // 关闭按钮
    lv_obj_t * popup_btn = lv_btn_create(popup_box);
    lv_obj_set_size(popup_btn, 80, 35);
    lv_obj_set_style_bg_color(popup_btn, btn_color, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(popup_btn, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(popup_btn, 10, LV_PART_MAIN);
    lv_obj_align(popup_btn, LV_ALIGN_BOTTOM_MID, 0, -15);
    
    lv_obj_t * btn_label = lv_label_create(popup_btn);
    lv_label_set_text(btn_label, "确定");
    lv_obj_set_style_text_color(btn_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(btn_label, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(btn_label);
    
    lv_obj_add_event_cb(popup_btn, close_popup_handler, LV_EVENT_CLICKED, NULL);
    
    if(auto_close_ms > 0) {
        popup_timer = lv_timer_create(popup_timer_cb, auto_close_ms, NULL);
        lv_timer_set_repeat_count(popup_timer, 1);
    }
}

static void show_success_message(const char *message, uint32_t auto_close_ms)
{
    show_custom_popup("成功", message,
                      lv_color_hex(0x2E7D32),
                      lv_color_hex(0xE8F5E9),
                      lv_color_hex(0x4CAF50),
                      lv_color_hex(0x4CAF50),
                      auto_close_ms);
}

static void show_error_message(const char *message, uint32_t auto_close_ms)
{
    show_custom_popup("错误", message,
                      lv_color_hex(0xC62828),
                      lv_color_hex(0xFFEBEE),
                      lv_color_hex(0xF44336),
                      lv_color_hex(0xF44336),
                      auto_close_ms);
}

static void show_warning_message(const char *message, uint32_t auto_close_ms)
{
    show_custom_popup("提示", message,
                      lv_color_hex(0xF57C00),
                      lv_color_hex(0xFFF3E0),
                      lv_color_hex(0xFF9800),
                      lv_color_hex(0xFF9800),
                      auto_close_ms);
}

// ========== 注册验证函数 ==========
static int validate_register_inputs(const char *phone, const char *password, 
                                     const char *confirm, char *err_msg, int err_size)
{
    // 1. 验证电话号码
    if(!phone || strlen(phone) == 0) {
        snprintf(err_msg, err_size, "请输入电话号码");
        return -1;
    }
    if(!is_valid_phone(phone)) {
        snprintf(err_msg, err_size, "电话号码必须为11位数字");
        return -2;
    }
    
    // 2. 验证密码
    if(!password || strlen(password) == 0) {
        snprintf(err_msg, err_size, "请输入密码");
        return -3;
    }
    if(strlen(password) < 6) {
        snprintf(err_msg, err_size, "密码长度不能少于6位");
        return -4;
    }
    
    // 3. 验证确认密码
    if(!confirm || strlen(confirm) == 0) {
        snprintf(err_msg, err_size, "请再次输入密码");
        return -5;
    }
    if(strcmp(password, confirm) != 0) {
        snprintf(err_msg, err_size, "两次输入的密码不一致");
        return -6;
    }
    
    // 4. 检查账号是否已存在
    if(find_user_by_phone(phone) >= 0) {
        snprintf(err_msg, err_size, "该电话号码已注册");
        return -7;
    }
    
    return 0;  // 验证通过
}

// ========== 隐藏键盘 ==========
static void hide_keyboard(void)
{
    if(ui_Keyboard3) {
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        keyboard_visible = 0;
    }
}

// ========== 显示键盘 ==========
static void show_keyboard_for_textarea(lv_obj_t * ta)
{
    if(!ui_Keyboard3 || !ta) return;
    _ui_keyboard_set_target(ui_Keyboard3, ta);
    _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    keyboard_visible = 1;
}

// ========== 延迟返回登录界面 ==========
static void delayed_return_to_login(lv_timer_t * timer)
{
    LV_UNUSED(timer);
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
}

// ========== 事件函数 ==========
void ui_event_Screen5(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        lv_obj_t * target = lv_event_get_target(e);
        if(target == ui_Screen5) {
            hide_keyboard();
        }
    }
}

void ui_event_TextArea5(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        show_keyboard_for_textarea(ui_TextArea5);
    }
}

void ui_event_TextArea6(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        show_keyboard_for_textarea(ui_TextArea6);
    }
}

void ui_event_TextArea7(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        show_keyboard_for_textarea(ui_TextArea7);
    }
}

// 注册按钮事件
void ui_event_Button3(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        // 如果键盘可见，不允许注册
        if(keyboard_visible) {
            show_warning_message("请先关闭键盘", 1500);
            return;
        }
        
        const char *phone = lv_textarea_get_text(ui_TextArea5);
        const char *password = lv_textarea_get_text(ui_TextArea6);
        const char *confirm = lv_textarea_get_text(ui_TextArea7);
        
        char err_msg[128];
        int result = validate_register_inputs(phone, password, confirm, err_msg, sizeof(err_msg));
        
        if(result == 0) {
            // 验证通过，执行注册
            int add_result = add_user(phone, password);
            if(add_result == 0) {
                show_success_message("注册成功！", 1500);
                
                // 清空输入框
                lv_textarea_set_text(ui_TextArea5, "");
                lv_textarea_set_text(ui_TextArea6, "");
                lv_textarea_set_text(ui_TextArea7, "");
                
                // 延迟返回登录界面
                lv_timer_t * timer = lv_timer_create(delayed_return_to_login, 1500, NULL);
                lv_timer_set_repeat_count(timer, 1);
            } else {
                show_error_message("注册失败，请重试", 2000);
            }
        } else {
            // 显示错误信息
            show_error_message(err_msg, 2000);
        }
    }
}

// 返回按钮事件
void ui_event_Button9(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        if(keyboard_visible) {
            show_warning_message("请先关闭键盘", 1500);
            return;
        }
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}

// ========== 屏幕初始化 ==========
void ui_Screen5_screen_init(void)
{
    // 加载已注册用户数据（使用共享函数）
    load_users_from_file();
    
    keyboard_visible = 0;
    password_visible1 = 0;
    password_visible2 = 0;
    
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_image_src(ui_Screen5, &ui_img_im4_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 键盘（放在 layer_top）
    ui_Keyboard3 = lv_keyboard_create(lv_layer_top());
    lv_obj_set_size(ui_Keyboard3, 1024, 250);
    lv_obj_align(ui_Keyboard3, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_radius(ui_Keyboard3, 20, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_Keyboard3, lv_color_hex(0xE5E1F0), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Keyboard3, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_Keyboard3, 10, LV_PART_ITEMS);
    lv_obj_set_style_bg_color(ui_Keyboard3, lv_color_hex(0xD9C9EF), LV_PART_ITEMS);
    lv_obj_set_style_bg_opa(ui_Keyboard3, 255, LV_PART_ITEMS);

    // 电话号码输入框
    ui_TextArea5 = lv_textarea_create(ui_Screen5);
    lv_obj_set_size(ui_TextArea5, 450, 55);
    lv_obj_align(ui_TextArea5, LV_ALIGN_CENTER, 0, -140);
    lv_textarea_set_placeholder_text(ui_TextArea5, "请输入11位电话号码");
    lv_textarea_set_one_line(ui_TextArea5, true);
    lv_obj_set_style_text_font(ui_TextArea5, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea5, 20, LV_PART_MAIN);
    lv_obj_set_style_pad_left(ui_TextArea5, 15, LV_PART_MAIN);

    ui_Label3 = lv_label_create(ui_Screen5);
    lv_obj_align_to(ui_Label3, ui_TextArea5, LV_ALIGN_OUT_LEFT_MID, -70, 0);
    lv_label_set_text(ui_Label3, "电话号码");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_myy2, LV_PART_MAIN);

    // 密码输入框
    ui_TextArea6 = lv_textarea_create(ui_Screen5);
    lv_obj_set_size(ui_TextArea6, 450, 55);
    lv_obj_align(ui_TextArea6, LV_ALIGN_CENTER, 0, -60);
    lv_textarea_set_placeholder_text(ui_TextArea6, "请输入密码（至少6位）");
    lv_textarea_set_password_mode(ui_TextArea6, true);
    lv_textarea_set_one_line(ui_TextArea6, true);
    lv_obj_set_style_text_font(ui_TextArea6, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea6, 20, LV_PART_MAIN);
    lv_obj_set_style_pad_left(ui_TextArea6, 15, LV_PART_MAIN);

    ui_Label4 = lv_label_create(ui_Screen5);
    lv_obj_align_to(ui_Label4, ui_TextArea6, LV_ALIGN_OUT_LEFT_MID, -70, 0);
    lv_label_set_text(ui_Label4, "密码");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_myy2, LV_PART_MAIN);

    // 密码可见性切换按钮
    pwd_visibility_btn1 = lv_btn_create(ui_TextArea6);
    lv_obj_set_size(pwd_visibility_btn1, 30, 30);
    lv_obj_align(pwd_visibility_btn1, LV_ALIGN_RIGHT_MID, -10, 0);
    lv_obj_set_style_bg_color(pwd_visibility_btn1, lv_color_hex(0xD9C9EF), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(pwd_visibility_btn1, 200, LV_PART_MAIN);
    lv_obj_set_style_radius(pwd_visibility_btn1, 15, LV_PART_MAIN);
    lv_obj_set_style_shadow_width(pwd_visibility_btn1, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(pwd_visibility_btn1, 0, LV_PART_MAIN);
    lv_obj_add_event_cb(pwd_visibility_btn1, toggle_password_visibility1, LV_EVENT_CLICKED, NULL);

    // 确认密码输入框
    ui_TextArea7 = lv_textarea_create(ui_Screen5);
    lv_obj_set_size(ui_TextArea7, 450, 55);
    lv_obj_align(ui_TextArea7, LV_ALIGN_CENTER, 0, 20);
    lv_textarea_set_placeholder_text(ui_TextArea7, "请再次输入密码");
    lv_textarea_set_password_mode(ui_TextArea7, true);
    lv_textarea_set_one_line(ui_TextArea7, true);
    lv_obj_set_style_text_font(ui_TextArea7, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea7, 20, LV_PART_MAIN);
    lv_obj_set_style_pad_left(ui_TextArea7, 15, LV_PART_MAIN);

    ui_Label5 = lv_label_create(ui_Screen5);
    lv_obj_align_to(ui_Label5, ui_TextArea7, LV_ALIGN_OUT_LEFT_MID, -70, 0);
    lv_label_set_text(ui_Label5, "确认密码");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_myy2, LV_PART_MAIN);

    // 确认密码可见性切换按钮
    pwd_visibility_btn2 = lv_btn_create(ui_TextArea7);
    lv_obj_set_size(pwd_visibility_btn2, 30, 30);
    lv_obj_align(pwd_visibility_btn2, LV_ALIGN_RIGHT_MID, -10, 0);
    lv_obj_set_style_bg_color(pwd_visibility_btn2, lv_color_hex(0xD9C9EF), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(pwd_visibility_btn2, 200, LV_PART_MAIN);
    lv_obj_set_style_radius(pwd_visibility_btn2, 15, LV_PART_MAIN);
    lv_obj_set_style_shadow_width(pwd_visibility_btn2, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(pwd_visibility_btn2, 0, LV_PART_MAIN);
    lv_obj_add_event_cb(pwd_visibility_btn2, toggle_password_visibility2, LV_EVENT_CLICKED, NULL);

    // 注册按钮
    ui_Button3 = lv_button_create(ui_Screen5);
    lv_obj_set_size(ui_Button3, 120, 50);
    lv_obj_align(ui_Button3, LV_ALIGN_CENTER, 60, 110);
    lv_obj_set_style_radius(ui_Button3, 25, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xD3C4E3), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN);

    ui_Label6 = lv_label_create(ui_Button3);
    lv_label_set_text(ui_Label6, "注册");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x595452), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(ui_Label6);

    // 返回按钮
    ui_Button9 = lv_button_create(ui_Screen5);
    lv_obj_set_size(ui_Button9, 100, 50);
    lv_obj_align(ui_Button9, LV_ALIGN_CENTER, -60, 110);
    lv_obj_set_style_radius(ui_Button9, 25, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0xD9CAEE), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN);

    ui_Label17 = lv_label_create(ui_Button9);
    lv_label_set_text(ui_Label17, "返回");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x7A6F85), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(ui_Label17);

    // 添加事件回调
    lv_obj_add_event_cb(ui_TextArea5, ui_event_TextArea5, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_TextArea6, ui_event_TextArea6, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_TextArea7, ui_event_TextArea7, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_CLICKED, NULL);
    
    // ===== 右上角时间显示 =====
    time_label = lv_label_create(ui_Screen5);
    lv_obj_set_style_text_color(time_label, lv_color_hex(0xB19AB3), LV_PART_MAIN);
    lv_obj_set_style_text_font(time_label, &lv_font_montserrat_24, LV_PART_MAIN);
    lv_obj_align(time_label, LV_ALIGN_TOP_RIGHT, -20, 20);
    update_time_cb(NULL);
    time_timer = lv_timer_create(update_time_cb, 1000, NULL);
    
    printf("[DEBUG] Screen5 initialized\n");
}

void ui_Screen5_screen_destroy(void)
{
    // 关闭弹窗
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
    
    if(time_timer) {
        lv_timer_del(time_timer);
        time_timer = NULL;
    }
    time_label = NULL;
    
    if(ui_Screen5) lv_obj_del(ui_Screen5);
    ui_Screen5 = NULL;
    ui_Keyboard3 = NULL;
    ui_TextArea5 = NULL;
    ui_TextArea6 = NULL;
    ui_TextArea7 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Button3 = NULL;
    ui_Label6 = NULL;
    ui_Button9 = NULL;
    ui_Label17 = NULL;
    pwd_visibility_btn1 = NULL;
    pwd_visibility_btn2 = NULL;
    
    keyboard_visible = 0;
    password_visible1 = 0;
    password_visible2 = 0;
    
    printf("[DEBUG] Screen5 destroyed\n");
}