// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include "lvgl.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <pthread.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <time.h>

static lv_obj_t * time_label = NULL;
static lv_timer_t * time_timer = NULL;

// 声明字体
LV_FONT_DECLARE(ui_font_myy2);
LV_FONT_DECLARE(ui_font_chinese);

// 全局变量
lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_TextArea3 = NULL;  // 问题输入框
lv_obj_t * ui_TextArea4 = NULL;  // 回答显示框
lv_obj_t * ui_Keyboard2 = NULL;  // 键盘对象（由IME管理）
lv_obj_t * ui_Button2 = NULL;     // 发送按钮
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Button10 = NULL;    // 返回按钮
lv_obj_t * ui_Label18 = NULL;

// IME 拼音输入法对象
static lv_obj_t * pinyin_ime = NULL;
static lv_obj_t * kb = NULL;

// 请求状态
static int is_requesting = 0;
static pthread_mutex_t request_mutex = PTHREAD_MUTEX_INITIALIZER;

// DeepSeek 配置
#define DEEPSEEK_PORT 11434
#define DEEPSEEK_IP "192.168.208.97"
#define BUFFER_SIZE 4096


static void update_time_cb(lv_timer_t * t)
{
    if(time_label) {
        time_t now = time(NULL);
        struct tm *tm_info = localtime(&now);
        char time_str[16];
        strftime(time_str, sizeof(time_str), "%H:%M", tm_info);  // 或 "%H:%M:%S"
        lv_label_set_text(time_label, time_str);
    }
}


// ========== 辅助函数 - 必须放在前面 ==========

// Unicode 转 UTF-8
static char* unicode_to_utf8(const char* unicode_str) 
{
    unsigned int code;
    sscanf(unicode_str, "%4x", &code);

    char* utf8 = NULL;
    if (code <= 0x7F) {
        utf8 = (char*)malloc(2);
        utf8[0] = (char)code;
        utf8[1] = '\0';
    } else if (code <= 0x7FF) {
        utf8 = (char*)malloc(3);
        utf8[0] = 0xC0 | (code >> 6);
        utf8[1] = 0x80 | (code & 0x3F);
        utf8[2] = '\0';
    } else if (code <= 0xFFFF) {
        utf8 = (char*)malloc(4);
        utf8[0] = 0xE0 | (code >> 12);
        utf8[1] = 0x80 | ((code >> 6) & 0x3F);
        utf8[2] = 0x80 | (code & 0x3F);
        utf8[3] = '\0';
    }
    return utf8;
}

// 解码 Unicode 转义序列
static char* decode_unicode_escapes(const char* input) 
{
    if (!input) return NULL;
    
    char* output = (char*)malloc(strlen(input) * 4 + 1);
    if (!output) return NULL;
    
    char* out_ptr = output;
    const char* in_ptr = input;

    while (*in_ptr) {
        if (strncmp(in_ptr, "\\u", 2) == 0) {
            char* utf8 = unicode_to_utf8(in_ptr + 2);
            if (utf8) {
                strcpy(out_ptr, utf8);
                out_ptr += strlen(utf8);
                free(utf8);
            }
            in_ptr += 6;
        } else {
            *out_ptr++ = *in_ptr++;
        }
    }
    *out_ptr = '\0';
    return output;
}

// 删除字符串中的子串
static void remove_substr(char *str, const char *sub) 
{
    if (!str || !sub) return;
    
    size_t sub_len = strlen(sub);
    if (sub_len == 0) return;

    char *pos;
    while ((pos = strstr(str, sub)) != NULL) {
        size_t tail_len = strlen(pos + sub_len) + 1;
        memmove(pos, pos + sub_len, tail_len);
    }
}

// ========== DeepSeek API 调用函数 ==========
static int get_deepseek_result(const char *question, char *response, int response_size)
{
    int sock = 0;
    struct sockaddr_in serv_addr;
    char request_body[2048];
    char request[4096];
    char buffer[BUFFER_SIZE];
    char allbuf[BUFFER_SIZE * 4] = {0};
    int total_received = 0;
    
    printf("=== DeepSeek API Call ===\n");
    printf("Question: %s\n", question);
    printf("Connecting to %s:%d...\n", DEEPSEEK_IP, DEEPSEEK_PORT);
    
    if ((sock = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
        printf("Socket creation error\n");
        return -1;
    }
    
    serv_addr.sin_family = AF_INET;
    serv_addr.sin_port = htons(DEEPSEEK_PORT);
    
    if (inet_pton(AF_INET, DEEPSEEK_IP, &serv_addr.sin_addr) <= 0) {
        printf("Invalid address\n");
        close(sock);
        return -2;
    }
    
    if (connect(sock, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) < 0) {
        printf("Connection Failed\n");
        close(sock);
        return -3;
    }
    
    printf("Connected!\n");
    
    // 转义 JSON 字符串
    char escaped_question[2048] = {0};
    char *src = (char*)question;
    char *dst = escaped_question;
    while(*src && (dst - escaped_question) < (int)sizeof(escaped_question) - 4) {
        if(*src == '"' || *src == '\\') {
            *dst++ = '\\';
        }
        *dst++ = *src++;
    }
    *dst = '\0';
    
    snprintf(request_body, sizeof(request_body), 
             "{\"model\":\"deepseek-r1:1.5b\",\"prompt\":\"%s\",\"stream\":false}", 
             escaped_question);
    
    snprintf(request, sizeof(request),
             "POST /api/generate HTTP/1.1\r\n"
             "Host: %s:%d\r\n"
             "Content-Type: application/json\r\n"
             "Content-Length: %zu\r\n"
             "Connection: close\r\n"
             "\r\n"
             "%s",
             DEEPSEEK_IP, DEEPSEEK_PORT, strlen(request_body), request_body);
    
    printf("Sending request (%zu bytes)...\n", strlen(request));
    
    if (send(sock, request, strlen(request), 0) < 0) {
        printf("Failed to send request\n");
        close(sock);
        return -4;
    }
    
    printf("Request sent, waiting for response...\n");
    
    int valread;
    while ((valread = read(sock, buffer, BUFFER_SIZE - 1)) > 0) {
        buffer[valread] = '\0';
        if (total_received + valread < (int)sizeof(allbuf) - 1) {
            strcat(allbuf + total_received, buffer);
            total_received += valread;
        } else {
            break;
        }
        
        if (strstr(allbuf, "}\r\n") || strstr(allbuf, "}\n")) {
            break;
        }
    }
    
    close(sock);
    printf("Total received: %d bytes\n", total_received);
    
    // 查找 HTTP 响应体
    char *body = strstr(allbuf, "\r\n\r\n");
    if (!body) {
        body = allbuf;
    } else {
        body += 4;
    }
    
    while(*body == ' ' || *body == '\t' || *body == '\n' || *body == '\r') body++;
    
    // ========== 新增：解析 JSON 并提取 response 字段 ==========
    // 这里需要引入 cJSON 库来处理 JSON
    
    // 临时方案：手动解析（保持原有逻辑，但增加 Unicode 解码）
    char *resp_start = NULL;
    const char *patterns[] = {"\"response\":\"", "\"response\": \"", "\"response\":  \""};
    
    for(int i = 0; i < 3; i++) {
        resp_start = strstr(body, patterns[i]);
        if(resp_start) {
            resp_start += strlen(patterns[i]);
            break;
        }
    }
    
    if(resp_start) {
        char *resp_end = strchr(resp_start, '"');
        if(resp_end) {
            int len = resp_end - resp_start;
            if(len >= response_size) len = response_size - 1;
            
            // 创建临时缓冲区存储原始响应
            char *temp_buf = (char*)malloc(len + 1);
            strncpy(temp_buf, resp_start, len);
            temp_buf[len] = '\0';
            
            // 解码 Unicode 转义序列
            char *decoded = decode_unicode_escapes(temp_buf);
            
            // 复制解码后的内容
            strncpy(response, decoded, response_size - 1);
            response[response_size - 1] = '\0';
            
            free(temp_buf);
            free(decoded);
            
            // 清理 think 标签
            remove_substr(response, "<think>");
            remove_substr(response, "</think>");
            
            // ========== 修复：彻底去除开头的换行符 ==========
            char *p = response;
            
            // 1. 跳过开头的所有换行符和空格
            while (*p == '\n' || *p == '\r' || *p == ' ') {
                p++;
            }
            
            // 2. 如果开头有跳过字符，移动字符串
            if (p != response) {
                memmove(response, p, strlen(p) + 1);
            }
            
            // 3. 清理中间多余的连续换行符（最多保留一个换行）
            char *src = response;
            char *dst = response;
            int newline_count = 0;
            
            while (*src) {
                if (*src == '\n') {
                    newline_count++;
                    if (newline_count <= 1) {  // 只保留一个换行
                        *dst++ = *src;
                    }
                } else {
                    newline_count = 0;
                    *dst++ = *src;
                }
                src++;
            }
            *dst = '\0';
            
            // 4. 去除结尾的换行符和空格
            int end = strlen(response) - 1;
            while (end >= 0 && (response[end] == '\n' || response[end] == '\r' || response[end] == ' ')) {
                response[end--] = '\0';
            }
            
            printf("Cleaned response: %s\n", response);
            return 0;
        }
    }
    
    snprintf(response, response_size, "无法解析 DeepSeek 响应\n\n原始响应: %.200s", body);
    return -5;
}




// ========== 文本框事件回调 ==========
static void ta_event_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = lv_event_get_target(e);
    
    if(code == LV_EVENT_FOCUSED) {
        if(lv_indev_get_type(lv_indev_active()) != LV_INDEV_TYPE_KEYPAD) {
            lv_keyboard_set_textarea(kb, ta);
            lv_obj_clear_flag(kb, LV_OBJ_FLAG_HIDDEN);
            // 同时显示候选词面板
            lv_obj_t * cand_panel = lv_ime_pinyin_get_cand_panel(pinyin_ime);
            if(cand_panel) {
                lv_obj_clear_flag(cand_panel, LV_OBJ_FLAG_HIDDEN);
            }
        }
    }
    else if(code == LV_EVENT_DEFOCUSED) {
        // 失去焦点时隐藏键盘
        lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
        lv_obj_t * cand_panel = lv_ime_pinyin_get_cand_panel(pinyin_ime);
        if(cand_panel) {
            lv_obj_add_flag(cand_panel, LV_OBJ_FLAG_HIDDEN);
        }
    }
    else if(code == LV_EVENT_CANCEL) {
        lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
        lv_obj_t * cand_panel = lv_ime_pinyin_get_cand_panel(pinyin_ime);
        if(cand_panel) {
            lv_obj_add_flag(cand_panel, LV_OBJ_FLAG_HIDDEN);
        }
        lv_obj_remove_state(ta, LV_STATE_FOCUSED);
        lv_indev_reset(NULL, ta);
    }
}


// ========== 异步回调 ==========
typedef struct {
    char response[4096];
} async_data_t;

static void async_update_response(void *data)
{
    async_data_t *async_data = (async_data_t*)data;
    if(ui_TextArea4 && async_data) {
        lv_textarea_set_text(ui_TextArea4, async_data->response);
    }
    if(data) free(data);
    
    if(ui_Button2) {
        lv_obj_clear_state(ui_Button2, LV_STATE_DISABLED);
    }
    pthread_mutex_lock(&request_mutex);
    is_requesting = 0;
    pthread_mutex_unlock(&request_mutex);
}

static void* deepseek_thread_func(void* arg)
{
    char* question = (char*)arg;
    async_data_t *async_data = (async_data_t*)malloc(sizeof(async_data_t));
    
    if(!async_data) {
        printf("Failed to allocate memory\n");
        if(question) free(question);
        return NULL;
    }
    
    memset(async_data->response, 0, sizeof(async_data->response));
    
    int ret = get_deepseek_result(question, async_data->response, sizeof(async_data->response));
    
    if(ret != 0) {
        snprintf(async_data->response, sizeof(async_data->response), 
                "DeepSeek 请求失败，错误码: %d\n\n请检查:\n1. Ollama 是否运行: ollama serve\n2. 模型是否下载: ollama pull deepseek-r1:1.5b\n3. IP 配置是否正确: %s:%d", 
                ret, DEEPSEEK_IP, DEEPSEEK_PORT);
    }
    
    lv_async_call(async_update_response, async_data);
    
    if(question) free(question);
    return NULL;
}

// ========== 发送按钮事件 ==========
void ui_event_Button2(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        pthread_mutex_lock(&request_mutex);
        if(is_requesting) {
            pthread_mutex_unlock(&request_mutex);
            lv_textarea_set_text(ui_TextArea4, "请等待上一个请求完成");
            return;
        }
        is_requesting = 1;
        pthread_mutex_unlock(&request_mutex);
        
        const char* raw_question = lv_textarea_get_text(ui_TextArea3);
        
        // 移除拼音提示部分
        char question[512];
        char *bracket = strrchr(raw_question, '[');
        if(bracket) {
            int len = bracket - raw_question;
            strncpy(question, raw_question, len);
            question[len] = '\0';
        } else {
            strcpy(question, raw_question);
        }
        
        // 去除末尾空白
        int len = strlen(question);
        while(len > 0 && (question[len-1] == ' ' || question[len-1] == '\n')) {
            question[--len] = '\0';
        }
        
        printf("Cleaned question: '%s' (len=%d)\n", question, strlen(question));
        
        if(strlen(question) == 0) {
            lv_textarea_set_text(ui_TextArea4, "请输入问题");
            pthread_mutex_lock(&request_mutex);
            is_requesting = 0;
            pthread_mutex_unlock(&request_mutex);
            return;
        }
        
        lv_textarea_set_text(ui_TextArea4, "正在思考中，请稍候...");
        lv_obj_add_state(ui_Button2, LV_STATE_DISABLED);
        
        pthread_t thread;
        pthread_create(&thread, NULL, deepseek_thread_func, strdup(question));
        pthread_detach(thread);
    }
}

// ========== 返回按钮事件 ==========
void ui_event_Button10(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_Screen2_screen_init);
    }
}

// ========== 屏幕点击事件 - 修复 NULL 指针问题 ==========
void ui_event_Screen3(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        lv_obj_t * target = lv_event_get_target(e);
        
        // 如果点击的不是输入框，隐藏键盘
        if(target != ui_TextArea3) {
            if(kb) {
                lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
            }
            if(pinyin_ime) {
                lv_obj_t * cand_panel = lv_ime_pinyin_get_cand_panel(pinyin_ime);
                if(cand_panel) {
                    lv_obj_add_flag(cand_panel, LV_OBJ_FLAG_HIDDEN);
                }
            }
            // 移除输入框焦点状态
            if(ui_TextArea3) {
                lv_obj_remove_state(ui_TextArea3, LV_STATE_FOCUSED);
            }
        }
    }
}

// ========== 屏幕初始化 ==========
void ui_Screen3_screen_init(void)
{
    printf("=== Initializing Screen3 ===\n");
    
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_image_src(ui_Screen3, &ui_img_3_png, LV_PART_MAIN | LV_STATE_DEFAULT);
     // 添加可点击标志，确保屏幕可以接收点击事件
    lv_obj_add_flag(ui_Screen3, LV_OBJ_FLAG_CLICKABLE);

    // ========== 问题输入框 ==========
    ui_TextArea3 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea3, 596);
    lv_obj_set_height(ui_TextArea3, 80);
    lv_obj_set_x(ui_TextArea3, -11);
    lv_obj_set_y(ui_TextArea3, -190);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "请输入问题...");
    lv_obj_set_style_text_font(ui_TextArea3, &ui_font_chinese, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea3, 20, LV_PART_MAIN);
    lv_obj_set_style_opa(ui_TextArea3, 230, LV_PART_MAIN);
    lv_obj_set_style_text_color(ui_TextArea3, lv_color_hex(0x999999), LV_PART_TEXTAREA_PLACEHOLDER);
    lv_obj_set_style_text_font(ui_TextArea3, &ui_font_chinese, LV_PART_TEXTAREA_PLACEHOLDER);
    
    // ========== 回答显示框 - 修改为可滚动 ==========
    ui_TextArea4 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea4, 596);
    lv_obj_set_height(ui_TextArea4, 150);
    lv_obj_set_x(ui_TextArea4, -11);
    lv_obj_set_y(ui_TextArea4, -57);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "等待回复中...");
    lv_obj_add_flag(ui_TextArea4, LV_OBJ_FLAG_SCROLLABLE);  // 保持可滚动
    lv_obj_set_scrollbar_mode(ui_TextArea4, LV_SCROLLBAR_MODE_AUTO);  // 自动显示滚动条
    lv_obj_set_scroll_dir(ui_TextArea4, LV_DIR_VER);  // 只允许垂直滚动
    lv_obj_set_style_text_font(ui_TextArea4, &ui_font_chinese, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea4, 20, LV_PART_MAIN);
    lv_obj_set_style_opa(ui_TextArea4, 230, LV_PART_MAIN);
    lv_obj_set_style_text_color(ui_TextArea4, lv_color_hex(0x999999), LV_PART_TEXTAREA_PLACEHOLDER);
    // 注意：移除了 LV_OBJ_FLAG_CLICKABLE，但仍然可以滚动
    lv_textarea_set_text(ui_TextArea4, "您好！我是DeepSeek\n\n使用说明：\n1. 点击输入框，键盘自动弹出\n2. 直接输入拼音（如 'ni'）\n3. 候选词面板会显示可选汉字\n4. 点击候选词选择汉字\n5. 点击「发送」获取回答");
    
    // ========== 拼音输入法 ==========
    pinyin_ime = lv_ime_pinyin_create(ui_Screen3);
    lv_obj_set_style_text_font(pinyin_ime, &ui_font_chinese, 0);
    
    kb = lv_keyboard_create(ui_Screen3);
    lv_ime_pinyin_set_keyboard(pinyin_ime, kb);
    lv_keyboard_set_textarea(kb, ui_TextArea3);
    lv_obj_add_event_cb(ui_TextArea3, ta_event_cb, LV_EVENT_ALL, NULL);
    
    // 候选词面板
    lv_obj_t * cand_panel = lv_ime_pinyin_get_cand_panel(pinyin_ime);
    lv_obj_set_size(cand_panel, LV_PCT(100), LV_PCT(8));
    lv_obj_align_to(cand_panel, kb, LV_ALIGN_OUT_TOP_MID, 0, 0);
    lv_obj_set_style_bg_color(cand_panel, lv_color_hex(0x333333), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(cand_panel, 200, LV_PART_MAIN);
    lv_obj_set_style_border_width(cand_panel, 1, LV_PART_MAIN);
    lv_obj_set_style_border_color(cand_panel, lv_color_hex(0x82569F), LV_PART_MAIN);
    lv_obj_add_flag(cand_panel, LV_OBJ_FLAG_HIDDEN);  // 初始隐藏
    
    // 键盘样式
    lv_obj_set_style_radius(kb, 20, LV_PART_MAIN);
    lv_obj_set_style_bg_color(kb, lv_color_hex(0xC3A9D5), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(kb, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(kb, 15, LV_PART_ITEMS);
    lv_obj_set_style_bg_color(kb, lv_color_hex(0x9E8ACF), LV_PART_ITEMS);
    lv_obj_set_style_bg_opa(kb, 255, LV_PART_ITEMS);
    lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
    
    // ========== 发送按钮 ==========
    ui_Button2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 368);
    lv_obj_set_y(ui_Button2, -80);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_Button2, 20, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x9C8AD6), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN);
    lv_obj_set_style_opa(ui_Button2, 240, LV_PART_MAIN);
    
    ui_Label2 = lv_label_create(ui_Button2);
    lv_label_set_text(ui_Label2, "发送");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(ui_Label2);
    
    // ========== 返回按钮 ==========
    ui_Button10 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button10, 100);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, -404);
    lv_obj_set_y(ui_Button10, -242);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Button10, 0, LV_PART_MAIN);
    
    ui_Label18 = lv_label_create(ui_Button10);
    lv_label_set_text(ui_Label18, "返回");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x777676), LV_PART_MAIN);
    lv_obj_set_style_text_decor(ui_Label18, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(ui_Label18);
    
    // ========== 添加事件回调 ==========
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);
    
    printf("=== Screen3 Initialization Complete ===\n");
    printf("中文输入：点击输入框 -> 输入拼音 -> 点击候选词选择汉字\n");

    // ===== 右上角时间显示 =====
    time_label = lv_label_create(ui_Screen3);  // X 替换为对应的屏幕编号
    lv_obj_set_style_text_color(time_label, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_text_font(time_label, &lv_font_montserrat_24, LV_PART_MAIN);
    lv_obj_align(time_label, LV_ALIGN_TOP_RIGHT, -20, 20);

    // 初始化时间显示
    update_time_cb(NULL);

    // 每秒更新一次时间
    time_timer = lv_timer_create(update_time_cb, 1000, NULL);
}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);
    ui_Screen3 = NULL;
    ui_TextArea3 = NULL;
    ui_TextArea4 = NULL;
    ui_Keyboard2 = NULL;
    ui_Button2 = NULL;
    ui_Label2 = NULL;
    ui_Button10 = NULL;
    ui_Label18 = NULL;
    pinyin_ime = NULL;
    kb = NULL;

    if(time_timer) {
    lv_timer_del(time_timer);
    time_timer = NULL;
    }
    time_label = NULL;
}