// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "../user_auth.h"

static lv_obj_t * time_label = NULL;
static lv_timer_t * time_timer = NULL;

// ========== UI对象声明 ==========
lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Keyboard4 = NULL;
lv_obj_t * ui_TextArea8 = NULL;
lv_obj_t * ui_TextArea9 = NULL;
lv_obj_t * ui_TextArea10 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label16 = NULL;

// 验证码相关
static lv_obj_t * ui_TextArea_code = NULL;
static lv_obj_t * ui_Label_code = NULL;
static char current_code[5];

// 密码可见性切换按钮（新密码）
static lv_obj_t * pwd_visibility_btn1 = NULL;

static int password_visible1 = 0;

// 密码可见性切换按钮（确认密码）
static lv_obj_t * pwd_visibility_btn2 = NULL;

static int password_visible2 = 0;

// 键盘状态
static int keyboard_visible = 0;

// 自定义弹窗相关
static lv_obj_t * popup_box = NULL;
static lv_obj_t * popup_mask = NULL;
static lv_timer_t * popup_timer = NULL;

static void update_time_cb(lv_timer_t * t)
{
    if(time_label) {
        time_t now = time(NULL);
        struct tm *tm_info = localtime(&now);
        char time_str[16];
        strftime(time_str, sizeof(time_str), "%H:%M", tm_info);
        lv_label_set_text(time_label, time_str);
    }
}

// ========== 生成验证码 ==========
static void generate_code(void)
{
    const char charset[] = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
    for(int i = 0; i < 4; i++) {
        current_code[i] = charset[rand() % (sizeof(charset) - 1)];
    }
    current_code[4] = '\0';
    if(ui_Label_code) {
        lv_label_set_text_fmt(ui_Label_code, "%s", current_code);
    }
}

// ========== 验证验证码 ==========
static int verify_code(const char *input)
{
    if(!input || strlen(input) == 0) return 0;
    return (strcmp(input, current_code) == 0);
}

// ========== 隐藏键盘 ==========
static void hide_keyboard(void)
{
    if(ui_Keyboard4) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        keyboard_visible = 0;
    }
}

// ========== 显示键盘 ==========
static void show_keyboard_for_textarea(lv_obj_t * ta)
{
    if(!ui_Keyboard4 || !ta) return;
    _ui_keyboard_set_target(ui_Keyboard4, ta);
    _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    keyboard_visible = 1;
}

// ========== 密码可见性切换（新密码）==========
// ========== 密码可见性切换（新密码）==========
static void toggle_password_visibility1(lv_event_t * e)
{
    LV_UNUSED(e);
    password_visible1 = !password_visible1;
    if(password_visible1) {
        lv_textarea_set_password_mode(ui_TextArea9, false);
        lv_obj_set_style_bg_color(pwd_visibility_btn1, lv_color_hex(0xB19AB3), LV_PART_MAIN);  // 可见时颜色加深
    } else {
        lv_textarea_set_password_mode(ui_TextArea9, true);
        lv_obj_set_style_bg_color(pwd_visibility_btn1, lv_color_hex(0xD9D1E8), LV_PART_MAIN);  // 隐藏时恢复原色
    }
}

// ========== 密码可见性切换（确认密码）==========
static void toggle_password_visibility2(lv_event_t * e)
{
    LV_UNUSED(e);
    password_visible2 = !password_visible2;
    if(password_visible2) {
        lv_textarea_set_password_mode(ui_TextArea10, false);
        lv_obj_set_style_bg_color(pwd_visibility_btn2, lv_color_hex(0xB19AB3), LV_PART_MAIN);
    } else {
        lv_textarea_set_password_mode(ui_TextArea10, true);
        lv_obj_set_style_bg_color(pwd_visibility_btn2, lv_color_hex(0xD9D1E8), LV_PART_MAIN);
    }
}

// ========== 自定义弹窗函数 ==========
static void close_popup_handler(lv_event_t * e)
{
    LV_UNUSED(e);
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
}

static void popup_timer_cb(lv_timer_t * timer)
{
    LV_UNUSED(timer);
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
}

static void show_custom_popup(const char *title, const char *message,
                               lv_color_t title_color, lv_color_t bg_color,
                               lv_color_t border_color, lv_color_t btn_color,
                               uint32_t auto_close_ms)
{
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
    
    // 创建背景遮罩
    popup_mask = lv_obj_create(lv_layer_top());
    lv_obj_set_size(popup_mask, LV_PCT(100), LV_PCT(100));
    lv_obj_set_style_bg_color(popup_mask, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(popup_mask, 100, LV_PART_MAIN);
    lv_obj_set_style_border_width(popup_mask, 0, LV_PART_MAIN);
    lv_obj_add_event_cb(popup_mask, close_popup_handler, LV_EVENT_CLICKED, NULL);
    
    // 创建弹窗容器
    popup_box = lv_obj_create(lv_layer_top());
    lv_obj_set_size(popup_box, 400, 200);
    lv_obj_set_style_bg_color(popup_box, bg_color, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(popup_box, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(popup_box, 20, LV_PART_MAIN);
    lv_obj_set_style_border_width(popup_box, 2, LV_PART_MAIN);
    lv_obj_set_style_border_color(popup_box, border_color, LV_PART_MAIN);
    lv_obj_set_style_shadow_width(popup_box, 20, LV_PART_MAIN);
    lv_obj_set_style_shadow_color(popup_box, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_shadow_opa(popup_box, 100, LV_PART_MAIN);
    lv_obj_center(popup_box);
    
    // 创建标题
    lv_obj_t * popup_title = lv_label_create(popup_box);
    lv_label_set_text(popup_title, title);
    lv_obj_set_style_text_color(popup_title, title_color, LV_PART_MAIN);
    lv_obj_set_style_text_font(popup_title, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_align(popup_title, LV_ALIGN_TOP_MID, 0, 15);
    
    // 创建消息文本
    lv_obj_t * popup_text = lv_label_create(popup_box);
    lv_label_set_text(popup_text, message);
    lv_obj_set_style_text_color(popup_text, lv_color_hex(0x333333), LV_PART_MAIN);
    lv_obj_set_style_text_font(popup_text, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_width(popup_text, 350);
    lv_label_set_long_mode(popup_text, LV_LABEL_LONG_WRAP);
    lv_obj_align(popup_text, LV_ALIGN_CENTER, 0, 0);
    
    // 创建关闭按钮
    lv_obj_t * popup_btn = lv_btn_create(popup_box);
    lv_obj_set_size(popup_btn, 80, 35);
    lv_obj_set_style_bg_color(popup_btn, btn_color, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(popup_btn, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(popup_btn, 10, LV_PART_MAIN);
    lv_obj_align(popup_btn, LV_ALIGN_BOTTOM_MID, 0, -15);
    
    lv_obj_t * btn_label = lv_label_create(popup_btn);
    lv_label_set_text(btn_label, "确定");
    lv_obj_set_style_text_color(btn_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(btn_label, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(btn_label);
    
    lv_obj_add_event_cb(popup_btn, close_popup_handler, LV_EVENT_CLICKED, NULL);
    
    if(auto_close_ms > 0) {
        popup_timer = lv_timer_create(popup_timer_cb, auto_close_ms, NULL);
        lv_timer_set_repeat_count(popup_timer, 1);
    }
}

static void show_success_message(const char *message, uint32_t auto_close_ms)
{
    show_custom_popup("成功", message,
                      lv_color_hex(0x2E7D32),
                      lv_color_hex(0xE8F5E9),
                      lv_color_hex(0x4CAF50),
                      lv_color_hex(0x4CAF50),
                      auto_close_ms);
}

static void show_error_message(const char *message, uint32_t auto_close_ms)
{
    show_custom_popup("错误", message,
                      lv_color_hex(0xC62828),
                      lv_color_hex(0xFFEBEE),
                      lv_color_hex(0xF44336),
                      lv_color_hex(0xF44336),
                      auto_close_ms);
}

static void show_warning_message(const char *message, uint32_t auto_close_ms)
{
    show_custom_popup("提示", message,
                      lv_color_hex(0xF57C00),
                      lv_color_hex(0xFFF3E0),
                      lv_color_hex(0xFF9800),
                      lv_color_hex(0xFF9800),
                      auto_close_ms);
}

// ========== 重设密码验证函数 ==========
static int reset_password(const char *phone, const char *new_password, 
                          const char *confirm_password, const char *code,
                          char *err_msg, int err_size)
{
    // 1. 验证电话号码
    if(!phone || strlen(phone) == 0) {
        snprintf(err_msg, err_size, "请输入电话号码");
        return -1;
    }
    if(!is_valid_phone(phone)) {
        snprintf(err_msg, err_size, "请输入11位数字电话号码");
        return -2;
    }
    
    // 2. 检查账号是否存在
    int idx = find_user_by_phone(phone);
    if(idx < 0) {
        snprintf(err_msg, err_size, "该账号不存在，请先注册");
        return -3;
    }
    
    // 3. 获取用户信息
    const AuthUser *user = get_user_by_index(idx);
    if(!user) {
        snprintf(err_msg, err_size, "系统错误");
        return -4;
    }
    
    // 4. 验证验证码
    if(!code || strlen(code) == 0) {
        snprintf(err_msg, err_size, "请输入验证码");
        return -5;
    }
    if(!verify_code(code)) {
        snprintf(err_msg, err_size, "验证码错误");
        return -6;
    }
    
    // 5. 验证新密码
    if(strlen(new_password) == 0) {
        snprintf(err_msg, err_size, "请输入新密码");
        return -7;
    }
    if(strlen(new_password) < 6) {
        snprintf(err_msg, err_size, "密码长度不能少于6位");
        return -8;
    }
    
    // 6. 检查新密码是否与原始密码相同
    if(strcmp(new_password, user->password) == 0) {
        snprintf(err_msg, err_size, "新密码不能与原始密码相同");
        return -9;
    }
    
    // 7. 验证确认密码
    if(strlen(confirm_password) == 0) {
        snprintf(err_msg, err_size, "请再次输入新密码");
        return -10;
    }
    if(strcmp(new_password, confirm_password) != 0) {
        snprintf(err_msg, err_size, "两次输入的密码不一致");
        return -11;
    }
    
    // 8. 更新密码
    int result = update_user_password(idx, new_password);
    if(result != 0) {
        snprintf(err_msg, err_size, "密码更新失败");
        return -12;
    }
    
    snprintf(err_msg, err_size, "密码重设成功！");
    return 0;
}

// 延迟切换屏幕的定时器回调
static void delayed_return_to_screen2(lv_timer_t * timer)
{
    LV_UNUSED(timer);
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
}

// ========== 事件函数 ==========
void ui_event_Screen6(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        lv_obj_t * target = lv_event_get_target(e);
        if(target == ui_Screen6) {
            hide_keyboard();
        }
    }
}

void ui_event_TextArea8(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        show_keyboard_for_textarea(ui_TextArea8);
    }
}

void ui_event_TextArea9(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        show_keyboard_for_textarea(ui_TextArea9);
    }
}

void ui_event_TextArea10(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        show_keyboard_for_textarea(ui_TextArea10);
    }
}

static void ui_event_TextArea_code(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        show_keyboard_for_textarea(ui_TextArea_code);
    }
}

static void code_click_event(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        generate_code();
    }
}

// 重设密码按钮事件
void ui_event_Button4(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        if(keyboard_visible) {
            show_warning_message("请先关闭键盘", 1500);
            return;
        }
        
        const char *phone = lv_textarea_get_text(ui_TextArea8);
        const char *new_password = lv_textarea_get_text(ui_TextArea9);
        const char *confirm_password = lv_textarea_get_text(ui_TextArea10);
        const char *code = lv_textarea_get_text(ui_TextArea_code);
        
        char err_msg[128];
        int result = reset_password(phone, new_password, confirm_password, code, err_msg, sizeof(err_msg));
        
        if(result == 0) {
            // 重设成功 - 显示成功弹窗
            show_success_message(err_msg, 1500);
            
            // 清空输入框
            lv_textarea_set_text(ui_TextArea8, "");
            lv_textarea_set_text(ui_TextArea9, "");
            lv_textarea_set_text(ui_TextArea10, "");
            lv_textarea_set_text(ui_TextArea_code, "");
            
            // 延迟返回登录界面
            lv_timer_t * timer = lv_timer_create(delayed_return_to_screen2, 1500, NULL);
            lv_timer_set_repeat_count(timer, 1);
        } else {
            // 重设失败 - 显示错误弹窗
            show_error_message(err_msg, 2000);
        }
        
        // 无论成功还是失败，都刷新验证码
        generate_code();
    }
}

// 返回按钮事件
void ui_event_Button8(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {
        if(keyboard_visible) {
            show_warning_message("请先关闭键盘", 1500);
            return;
        }
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}

// ========== 屏幕初始化 ==========
void ui_Screen6_screen_init(void)
{
    srand(time(NULL));
    
    // 加载用户数据
    load_users_from_file();
    
    keyboard_visible = 0;
    password_visible1 = 0;
    password_visible2 = 0;
    
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_image_src(ui_Screen6, &ui_img_im1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 键盘（放在 layer_top）
    ui_Keyboard4 = lv_keyboard_create(lv_layer_top());
    lv_obj_set_size(ui_Keyboard4, 1024, 230);
    lv_obj_align(ui_Keyboard4, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_obj_add_flag(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_radius(ui_Keyboard4, 20, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_Keyboard4, lv_color_hex(0xE9E8F1), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Keyboard4, 255, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_Keyboard4, 15, LV_PART_ITEMS);
    lv_obj_set_style_bg_color(ui_Keyboard4, lv_color_hex(0xD9D1E8), LV_PART_ITEMS);
    lv_obj_set_style_bg_opa(ui_Keyboard4, 255, LV_PART_ITEMS);

        // ===== 电话号码输入框 =====
    ui_TextArea8 = lv_textarea_create(ui_Screen6);
    lv_obj_set_size(ui_TextArea8, 450, 55);
    lv_obj_align(ui_TextArea8, LV_ALIGN_CENTER, 0, -200);  // 向右移动，向上移动
    lv_textarea_set_placeholder_text(ui_TextArea8, "请输入11位电话号码");
    lv_textarea_set_one_line(ui_TextArea8, true);
    lv_obj_set_style_text_font(ui_TextArea8, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea8, 20, LV_PART_MAIN);
    lv_obj_set_style_pad_left(ui_TextArea8, 15, LV_PART_MAIN);  // 文字与左边框的间距

    ui_Label7 = lv_label_create(ui_Screen6);
    lv_obj_align_to(ui_Label7, ui_TextArea8, LV_ALIGN_OUT_LEFT_MID, -70, 0);  // 增加一个字的间隔
    lv_label_set_text(ui_Label7, "电话号码");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_myy2, LV_PART_MAIN);

    // ===== 新密码输入框 =====
    ui_TextArea9 = lv_textarea_create(ui_Screen6);
    lv_obj_set_size(ui_TextArea9, 450, 55);
    lv_obj_align(ui_TextArea9, LV_ALIGN_CENTER, 0, -125);  // 向右移动，向上移动
    lv_textarea_set_placeholder_text(ui_TextArea9, "请输入新密码（至少6位）");
    lv_textarea_set_password_mode(ui_TextArea9, true);
    lv_textarea_set_one_line(ui_TextArea9, true);
    lv_obj_set_style_text_font(ui_TextArea9, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea9, 20, LV_PART_MAIN);
    lv_obj_set_style_pad_left(ui_TextArea9, 15, LV_PART_MAIN);

    ui_Label8 = lv_label_create(ui_Screen6);
    lv_obj_align_to(ui_Label8, ui_TextArea9, LV_ALIGN_OUT_LEFT_MID, -70, 0);
    lv_label_set_text(ui_Label8, "新密码");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_myy2, LV_PART_MAIN);

    // 新密码可见性切换按钮（纯色小按钮，无标签）
    pwd_visibility_btn1 = lv_btn_create(ui_TextArea9);
    lv_obj_set_size(pwd_visibility_btn1, 30, 30);  // 稍小一点
    lv_obj_align(pwd_visibility_btn1, LV_ALIGN_RIGHT_MID, -10, 0);
    lv_obj_set_style_bg_color(pwd_visibility_btn1, lv_color_hex(0xD9D1E8), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(pwd_visibility_btn1, 200, LV_PART_MAIN);
    lv_obj_set_style_radius(pwd_visibility_btn1, 15, LV_PART_MAIN);
    lv_obj_set_style_shadow_width(pwd_visibility_btn1, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(pwd_visibility_btn1, 0, LV_PART_MAIN);
    lv_obj_add_event_cb(pwd_visibility_btn1, toggle_password_visibility1, LV_EVENT_CLICKED, NULL);

    // ===== 确认密码输入框 =====
    ui_TextArea10 = lv_textarea_create(ui_Screen6);
    lv_obj_set_size(ui_TextArea10, 450, 55);
    lv_obj_align(ui_TextArea10, LV_ALIGN_CENTER, 0, -50);  // 向右移动，向上移动
    lv_textarea_set_placeholder_text(ui_TextArea10, "请再次输入新密码");
    lv_textarea_set_password_mode(ui_TextArea10, true);
    lv_textarea_set_one_line(ui_TextArea10, true);
    lv_obj_set_style_text_font(ui_TextArea10, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea10, 20, LV_PART_MAIN);
    lv_obj_set_style_pad_left(ui_TextArea10, 15, LV_PART_MAIN);

    ui_Label9 = lv_label_create(ui_Screen6);
    lv_obj_align_to(ui_Label9, ui_TextArea10, LV_ALIGN_OUT_LEFT_MID, -70, 0);
    lv_label_set_text(ui_Label9, "确认密码");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_myy2, LV_PART_MAIN);

    // 确认密码可见性切换按钮（纯色小按钮，无标签）
    pwd_visibility_btn2 = lv_btn_create(ui_TextArea10);
    lv_obj_set_size(pwd_visibility_btn2, 30, 30);
    lv_obj_align(pwd_visibility_btn2, LV_ALIGN_RIGHT_MID, -10, 0);
    lv_obj_set_style_bg_color(pwd_visibility_btn2, lv_color_hex(0xD9D1E8), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(pwd_visibility_btn2, 200, LV_PART_MAIN);
    lv_obj_set_style_radius(pwd_visibility_btn2, 15, LV_PART_MAIN);
    lv_obj_set_style_shadow_width(pwd_visibility_btn2, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(pwd_visibility_btn2, 0, LV_PART_MAIN);
    lv_obj_add_event_cb(pwd_visibility_btn2, toggle_password_visibility2, LV_EVENT_CLICKED, NULL);

    // ===== 验证码输入框 =====
    ui_TextArea_code = lv_textarea_create(ui_Screen6);
    lv_obj_set_size(ui_TextArea_code, 260, 55);
    lv_obj_align(ui_TextArea_code, LV_ALIGN_CENTER, -40, 25);  // 向上移动，确保在键盘上方
    lv_textarea_set_placeholder_text(ui_TextArea_code, "验证码");
    lv_textarea_set_one_line(ui_TextArea_code, true);
    lv_obj_set_style_text_font(ui_TextArea_code, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_TextArea_code, 20, LV_PART_MAIN);
    lv_obj_set_style_pad_left(ui_TextArea_code, 15, LV_PART_MAIN);

    lv_obj_t * label_code_text = lv_label_create(ui_Screen6);
    lv_obj_align_to(label_code_text, ui_TextArea_code, LV_ALIGN_OUT_LEFT_MID, -50, 0);  // 增加间隔
    lv_label_set_text(label_code_text, "验证码");
    lv_obj_set_style_text_font(label_code_text, &ui_font_myy2, LV_PART_MAIN);

    // ===== 验证码显示按钮 =====
    lv_obj_t * btn_code = lv_button_create(ui_Screen6);
    lv_obj_set_size(btn_code, 120, 55);
    lv_obj_align_to(btn_code, ui_TextArea_code, LV_ALIGN_OUT_RIGHT_MID, 15, 0);
    lv_obj_set_style_bg_color(btn_code, lv_color_hex(0xD9D1E8), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(btn_code, 255, LV_PART_MAIN);
    lv_obj_set_style_border_width(btn_code, 0, LV_PART_MAIN);
    lv_obj_set_style_radius(btn_code, 15, LV_PART_MAIN);

    ui_Label_code = lv_label_create(btn_code);
    lv_label_set_text(ui_Label_code, "----");
    lv_obj_center(ui_Label_code);
    lv_obj_set_style_text_font(ui_Label_code, &lv_font_montserrat_24, LV_PART_MAIN);
    lv_obj_set_style_text_color(ui_Label_code, lv_color_hex(0x333333), LV_PART_MAIN);


    // ===== 重设密码按钮 =====
    ui_Button4 = lv_button_create(ui_Screen6);
    lv_obj_set_size(ui_Button4, 120, 50);
    lv_obj_align(ui_Button4, LV_ALIGN_CENTER, 0, 140);
    lv_obj_set_style_radius(ui_Button4, 25, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xD9D1E8), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN);

    ui_Label10 = lv_label_create(ui_Button4);
    lv_label_set_text(ui_Label10, "重设密码");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x3F3A36), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(ui_Label10);

    // ===== 返回按钮 =====
    ui_Button8 = lv_button_create(ui_Screen6);
    lv_obj_set_size(ui_Button8, 80, 40);
    lv_obj_align(ui_Button8, LV_ALIGN_TOP_LEFT, 20, 20);
    lv_obj_set_style_radius(ui_Button8, 15, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xD9D1E8), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Button8, 230, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_Button8, 1, LV_PART_MAIN);
    lv_obj_set_style_border_color(ui_Button8, lv_color_hex(0xB19AB3), LV_PART_MAIN);

    ui_Label16 = lv_label_create(ui_Button8);
    lv_label_set_text(ui_Label16, "返回");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x3F3A36), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_myy2, LV_PART_MAIN);
    lv_obj_center(ui_Label16);

    // ===== 右上角时间显示 =====
    time_label = lv_label_create(ui_Screen6);
    lv_obj_set_style_text_color(time_label, lv_color_hex(0xB19AB3), LV_PART_MAIN);
    lv_obj_set_style_text_font(time_label, &lv_font_montserrat_24, LV_PART_MAIN);
    lv_obj_align(time_label, LV_ALIGN_TOP_RIGHT, -20, 20);
    update_time_cb(NULL);
    time_timer = lv_timer_create(update_time_cb, 1000, NULL);

    // 事件绑定
    lv_obj_add_event_cb(ui_TextArea8, ui_event_TextArea8, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_TextArea9, ui_event_TextArea9, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_TextArea10, ui_event_TextArea10, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_TextArea_code, ui_event_TextArea_code, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(btn_code, code_click_event, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_CLICKED, NULL);

    // 生成初始验证码
    generate_code();
    
    printf("[DEBUG] Screen6 initialized\n");
}

void ui_Screen6_screen_destroy(void)
{
    if(popup_timer) {
        lv_timer_del(popup_timer);
        popup_timer = NULL;
    }
    if(popup_mask) {
        lv_obj_del(popup_mask);
        popup_mask = NULL;
    }
    if(popup_box) {
        lv_obj_del(popup_box);
        popup_box = NULL;
    }
    
    if(time_timer) {
        lv_timer_del(time_timer);
        time_timer = NULL;
    }
    time_label = NULL;
    
    if(ui_Screen6) lv_obj_del(ui_Screen6);
    ui_Screen6 = NULL;
    ui_Keyboard4 = NULL;
    ui_TextArea8 = NULL;
    ui_TextArea9 = NULL;
    ui_TextArea10 = NULL;
    ui_TextArea_code = NULL;
    ui_Label_code = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Button4 = NULL;
    ui_Label10 = NULL;
    ui_Button8 = NULL;
    ui_Label16 = NULL;
    pwd_visibility_btn1 = NULL;
    pwd_visibility_btn2 = NULL;
   
    
    keyboard_visible = 0;
    password_visible1 = 0;
    password_visible2 = 0;
    
    printf("[DEBUG] Screen6 destroyed\n");
}